### ISSUE TITLE
Pass verse reference to external resources

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#102]
I have some resources that are available at URL's that would easily load in an iframe, but I can't seem to setup resource panes for them. I find some related discussion and it seems there isn't a feature like this, so I'm proposing one.

It would be nice if the URL for external resources could pass some parameters in the URL, especially and OSIS range and/or reference or range that matches the open and open passage and or focused verse.

**Comment by teusbenschop** [comment]
Yes, a general resource page, where all parameters can be set by the user, is not available as of now, and it would be nice to have one. Currently the resource name, the book, chapter and verse are passed to a resource request, so if those can be translated to an URL to fetch, that would do. But then one gets the entire page. The majority of resources also do post-fetch filtering, to just get the bit that is wanted, without the clutter. While creating the URL based on the passage seems the easier part, creating the post-fetch filter, and making it general, seems harder. One could of course start with just getting the plain text.

**Comment by alerque** [comment]
The resources I have  in mind are either on a server that I control (other bible translations and image resources) that can be queried and return results appropriate for embedding or can be queried via an API ar otherwise be proxied through something external that did the post-fetch filtering and returned a ready to embed page. I wasn't thinking so much of listing these as resources so much as using them as iframe sources as part of a workbench. As an advanced setup feature just being able to pass URL parameters would do the trick, writing a data scraper isn't necessary.

**Comment by alerque** [comment]
Just a heads up because I happened to notice this on the current iframe system: if/when we allow external URLs to be loaded into the app we need to drop the `allow-scripts` and/or `allow-same-origin` properties of the iframe, otherwise we'll be punching a wide open security whole.

**Comment by teusbenschop** [comment]
So far, as it is now at least, the iframe when it loads a resource does not fetch the content itself, but fetches the content from the server, and the server actually filters the page, so all dangerous stuff is filtered out (hopefully). if the "allow-scripts" is dropped, then the current clients-side javascript won't run, and that again cripples the Bible text editors and other pages that have javascript.

**Comment by teusbenschop** [comment]
Since this resource will be an URL, basically, that loads in an iframe, it means that installing this resource locally on the device is going to be hard, and this again means that the resource will have to be fetched through the network each time, and that one cannot work offline and expect the resource to show up.

**Comment by teusbenschop** [comment]
>  I wasn't thinking so much of listing these as resources so much as using them as iframe sources as part of a workbench. 

Just thinking: When the user-defined resources, as proposed in this issue, would be loaded as one resource in the current list of Resources, as part of the Workbench, that would more clearly show that this is a Resource. And one could create several user-defined resources, and load them all in the Resources, and when there were enough of them, it would scroll, as the current Resources already do.

But perhaps the above does not make sense to you. What do you think?

**Comment by alerque** [comment]
The resources I'm thinking of would not be something we could cache offline anyway, working online would be a given. The iframe model makes sense  for this, and having it on a separate workbench by itself rather than being mixed in with BE's internal resources makes sense to me.

An extra thought is that besides a placeholder that would pass a full BCV reference as part of a URL, it should be flexible enough to also pass BCV parts. For example if a resource only had chapter level granularity available we should be able to pass just the chapter number and save a lot of reloading the resource while navigating around the chapter. Some resources might also take the verse as a hash  parameter so that the focus could be updated without reloading the resource.

**Comment by teusbenschop** [comment]
If this type of resource would be available in the Cloud, and not available from a Client, that would save some logic from the client to download the resource configurations from the cloud. So I guess the questions is whether (1) it would be sufficient to have this only in the Cloud? Or whether (2) it should be available in the clients also? Everything is possible of course, just that (2) is more work than (1).

**Comment by teusbenschop** [comment]
The above question about whether this type is available on clients can be cancelled because I've found an easy way to transfer the user-defined resource configurations to the clients. So, let's have them on the clients also.

**Comment by teusbenschop** [comment]
The mechanics of creating and displaying the user-defined web resources is now operational with the last commit. You were mentioning about the security impact of running external web content in the browser. The iframe element now is sandboxed like this:

```
  <iframe sandbox="allow-forms" src="http://localhost:8080/search/index" style="flex-grow: 1"></iframe>
```

I hope that this is secure enough.
Let me remove "allow-forms" also and do another commit, because the less stuff is allowed, the better it is for security :)
