### ISSUE TITLE
Setting the Desktop width no longer works

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#103]
Copied from comments on #101:

> In the desktop editor, setting the Desktop width: to e.g. 100% or 2000px no longer works. When leaving this empty, the desktops work as expected. When entering the above values, the desktops no longer display the contents of the iframes.

**Comment by alerque** [comment]
This one is nettling me a little bit. How this was getting passed to the layout is definitely wrong, but I fixed that. Now the problem is I can't get anything out of the settings database besides a 1. No matter what value I save (and the settings come back in the editor) the value I get in the actual layout is "1". Anything come to mind off the top of your head?

``` cpp
string workbenchwidth = workbench_get_entire_width (request);
if (!workbenchwidth.empty ()) {
  workbenchwidth.insert (0, "width: ");
  workbenchwidth.append (";");
}
view.set_variable ("workbenchwidth", workbenchwidth);
```

This is only ever giving me `width: 1;`.

**Comment by teusbenschop** [comment]
I had that problem yesterday also, then didn't think of it till now.
In the mean time I had thrown out all desktops, and created new one.

``` cpp
 string workbenchwidth = workbench_get_entire_width (request);
  cout << workbenchwidth << endl; // Todo
  if (!workbenchwidth.empty ()) {
    workbenchwidth.insert (0, "; width: ");
    workbenchwidth.append ("; margin: 0 auto; overflow: hidden;");
  }
  cout << workbenchwidth << endl; // Todo
  view.set_variable ("workbenchwidth", workbenchwidth);
```

The new config settings behaves well: The above code produces the expected values:

```
Listening on http://localhost:8080
Press Ctrl-C to quit
20
; width: 20; margin: 0 auto; overflow: hidden;

```

**Comment by alerque** [comment]
I found the issue here. The other legacy width values are being stripped of units so they work as factors, but it needs to not apply to this setting.

**Comment by teusbenschop** [comment]
Great!

**Comment by teusbenschop** [comment]
Thinking about using factors rather than percentages or pixels: When a user would enter a desktop width of 2 (taking "2" as a factor meaning double the width of the current screen size), that would be easier for the user rather than entering, for example, "2000px". Because most users do not know the width in pixels of their screen. Then when using the same desktop from other devices, the "2000px" would work differently on different devices, but a factor of "2" always would give double the screen width.

**Comment by teusbenschop** [comment]
By the way, definitely, the new desktop layout looks beautiful! It looks much better than it looked before. It is appealing to the eye to see this new desktop layout.

**Comment by alerque** [comment]
> Thinking about using factors rather than percentages or pixels: When a user would enter a desktop width of 2 (taking "2" as a factor meaning double the width of the current screen size), that would be easier for the user rather than entering, for example, "2000px". Because most users do not know the width in pixels of their screen. Then when using the same desktop from other devices, the "2000px" would work differently on different devices, but a factor of "2" always would give double the screen width.

This _could_ be done with some fancy math, but at the moment I'm not seeing the benefit. The factor system always specifies some portion of the available space. A factor of 1 and 56 will both  be 100% in the case of one pane. The number is meaningless until there is a second pane to give/take space to/from.

The only case where the desktop width setting is useful now is when you want to break out of the overall app size being 100% width. You can't set this with a flex box factor, you have to use some other CSS unit. In the current implementation either px or % work just like they did before. This should cover either use case of wanting a fixed area or having an area relative to  the screen size. Other units like `vw` and friends are also available. If we wanted to hack this so the user could only use something that worked like a factor but for the screen shape we would just force this to be an int, multiply  by 100 and add `vw` units. But I really don't see the use in limiting what the user _could_ do with this value to account for odd edge cases.

Realistically I think the future of this setting is to drop it entirely and have an alternative way of dealing with panes for small screens, but that's another story.

**Comment by teusbenschop** [comment]
Yes, I now realize again that setting the width as a percentage is all what is needed for a user to adapt to various screen widths.
