### ISSUE TITLE
Journal content overflows workspace 

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#105]
Copied from comments on #101:

> On the Mac, the link to clear the entire journal does not remain at the bottom of the page, but scrolls along with and mixes with the journal entries, leaving users in the dark about how to clear the journal as they don't find the link anymore in cases of long journals.
> 
> ![](https://cloud.githubusercontent.com/assets/1310167/14610439/3da231d2-058e-11e6-882e-f68c558021fb.png)
> 
> The above occurs in the OSX port and also with Safari.
> 
> On iOS, the link for clearing the journal shifts off the screen also, like on OSX.

**Comment by alerque** [comment]
This is a function of bogus Javascript animation. The wrong values were being used for calculations all along but it wasn't evident until the DOM changed.

**Comment by teusbenschop** [comment]
Ah, so it got away with it for some time :) Thanks!

**Comment by teusbenschop** [comment]
With the fixed DOM, the overall impression is that the whole app feels faster on the iPad.

**Comment by alerque** [comment]
By setting up the layout based on the window and not allowing it to recalculate the overall layout based on the contents of each area, the browser has to do a lot less repainting of the entire canvas space and can focus on just the bits that changed with any given activity. Also with fewer nested items that trigger layout recalculations, even full repaints take fewer iterations over the DOM to calculate where everything ends up.

**Comment by teusbenschop** [comment]
I can clearly see that the new CSS has advantages as to speed, and I believe everything you say about it, but it is way beyond my understanding which CSS bits are crucial here :)
