### ISSUE TITLE
Bible editor not editable on client separate from Cloud

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#106]
Copied from comments on #101:

> On Android it fails to edit the Bible text. Although the text is supposed to be editable, it is not editable on a Nexus 6 running Android 6.0.1.

**Comment by alerque** [comment]
Are you able to replicate this in the AOSP/Stock browser or is it just in a compiled version of the app with the embedded browser widget?

**Comment by teusbenschop** [comment]
It occurs in the embedded browser widget, plus from Chrome when connecting to it from outside. See the screenshot, where the editor's contenteditable property is set to false. So it's a software thing, not a browser thing.
![screen shot 2016-04-19 at 09 23 12](https://cloud.githubusercontent.com/assets/1310167/14630856/97e33470-0610-11e6-8da5-38668e459715.png)

**Comment by alerque** [comment]
The source code pretty much hard codes `contenteditable="true"`, at least from the HTML side. Can you disable Javascript in Chrome (from the settings in the `⋮` menu in your dev tools panel) and refresh that page, then find that  same line in the source and see how it reads? I realize the actual Bible content won't render properly but it should load enough of the page layout code to have that line.

**Comment by teusbenschop** [comment]
After doing that, it reads

```
<div id="editor" class="bibleeditor customa4398d" contenteditable="true"></div>
```

**Comment by teusbenschop** [comment]
The Javascript bit receives the chapter content from the server, and along with it comes a value that says whether the user has write access to this Bible. Which means that either Javascript is not setting the contenteditable value to "true" or else the server on Android thinks that the user does not have write access to this chapter.

**Comment by alerque** [comment]
This, as well as #108, probably have to do with the fact that I fixed a long-uncaught issue with the DOM. There were multiple cases where more than one element with the same id were on the same page and I converted as many of these to classes as I  saw while fixing the layout. That was always a no-no and would have caused erratic behavior in  some browsers, but somehow you got away with it for a while.

There is a note on [L99 of `lib/edit/index.js`](https://github.com/teusbenschop/bibledit/blob/master/lib/edit/index.js#L99) that seems like it might relate to this, and on line 130 the Javascript looking for "the" editor by ID is probably broken. Strange why it would find an area to _disable_ and not to then _enable_ it, but this bit of code makes no sense to me at all yet.

**Comment by alerque** [comment]
The `<div id="editor">` elements seem to have survived my refactoring (probably because they get loaded one at a time in their own iframes), so that this isn't quite that simple.

**Comment by alerque** [comment]
> Which means that either Javascript is not setting the contenteditable value to "true" or else the server on Android thinks that the user does not have write access to this chapter.

You can you figure out which of these it is by setting a breakpoint on line 128 of edit/index.js in your Chrome dev tools and refreshing the page, then looking at the values of `response` and `editorWriteAccess` when it stops on the breakpoint.

I'm a little hog-tied in that I still can't reproduce this one locally.

**Comment by teusbenschop** [comment]
Looking at the values after the breakpoint, it looks like the server thinks that the user has no write access.
![screen shot 2016-04-19 at 11 21 17](https://cloud.githubusercontent.com/assets/1310167/14634182/13bad318-0621-11e6-985d-71157cd429af.png)

**Comment by alerque** [comment]
How confident are you that your user on this test instance actually has edit privs and that your app isn't compiled with source code changes not part of my set? So far I'm struggling for clues based on the code changes I made.

**Comment by teusbenschop** [comment]
As they say, great minds think alike: I also think that it will be unrelated to your set of changes. It must be something else. I'll assign this issue to myself for looking into it.

**Comment by teusbenschop** [comment]
The behaviour issue appears to be fixed after connecting it to Bibledit Cloud, and doing a sync with the Cloud. After that, the Bible becomes editable.
It would be desirable that a Bible would also be editable when not being connected to the Cloud.
It would be for demo purposes only.
The data of the edited Bible, when not connected to the Cloud, would be hard to extract from the device by normal users.

**Comment by teusbenschop** [comment]
Looking into this now, it not only shows the behaviour on Android. The client configuration on the development machine also behaves like this.
