### ISSUE TITLE
Search results link to to editor from Blink/Webkit browsers broken

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#108]
Copied from comments on #101:

> On Android, when doing a search, then clicking the passage link in one of the search results, it says that the passage has been opened in the existing editor, yet it has not been opened at all.

**Comment by alerque** [comment]
This is not Android specific. I replicated it from Chrome on a desktop build (but it works in Firefox).

**Comment by teusbenschop** [comment]
I fail to replicate it on Chrome on a Mac.
It may be a timing issue.
The editors send signals to the server, through AJAX, telling the server that an editor is available.
If the signals stop coming, the server knows that no editor is available. If the signals are still coming in, the server assumes an editor is available, and says that the passage has been opened in an existing editor. There's a timeout on those signals of a few seconds, i.e. if the signals don't come in for a few seconds, the server still assumes an editor is opened.
Not sure of this information helps though...

**Comment by alerque** [comment]
Why would the sever need to tell the client whether it has an editor open. Shouldn't this communication and check for and available widget happen purely client side?

**Comment by teusbenschop** [comment]
It would be better if this happens at the client side. But in case the user has one browser open, with the Bible editor in one tab, and the Search page in another tab, how would the tabs communicate with one another?

**Comment by alerque** [comment]
There are normal mechanisms for doing that. Part of the problem here is the home-brewed sessions management is broken (see #94).

**Comment by teusbenschop** [comment]
If part of the solution to getting this client-side is to fix the session management as described in #94, then there is a good reason to fix this session management. Because if the client could find out whether the browser has an active editor open, without the help of the server, that would be helpful. It also would reduce the traffic between the client and the server.

**Comment by teusbenschop** [comment]
The original error cannot be reproduced in the newest Android release anymore: It is now working as it has always done, and as expected.
