### ISSUE TITLE
Cannot see the resources in Bibledit Client / Settings / Resources

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#126]
The Resources cannot be seen in a Bibledit Client anymore.
![screen shot 2016-04-20 at 08 47 37](https://cloud.githubusercontent.com/assets/1310167/14665608/945b58fe-06d4-11e6-8002-795e3eac8fbc.png)

**Comment by teusbenschop** [comment]
This is on Mac OSX, with the embedded widget that comes with the native Bibledit.

**Comment by teusbenschop** [comment]
The behaviour is also visible with Safari.

**Comment by alerque** [comment]
Would you mind either a) assigning this and the other layout  related bugs to me or b) adding me as a  contributor to this repo so I can help manage issues?

**Comment by alerque** [comment]
I can't find what page is broken from Safari. Is this only when connecting to the OSX app instance or should I expect to find it using Safari to connect to a cloud instance as well? If the latter, what's the URL path of the page in question here?

**Comment by teusbenschop** [comment]
Yes, I like the idea of you being able to push to this repository to help, and for being able to manage issues. I have added you as a contributor, and hope that it works. Thanks for all the help and assistance :)

**Comment by teusbenschop** [comment]
Here's the URL showing the problem from Safari:
http://bibledit.org:8080/notes/note?id=536656468

**Comment by teusbenschop** [comment]
Oops, wrong URL: The URL shows the problem with the notes (which is another issue).

**Comment by teusbenschop** [comment]
Here is the correct URL that, when opened from Safari, shows problems:
http://bibledit.org:8080/resource/sword

**Comment by teusbenschop** [comment]
There's actually separate links for the Settings / Resources in Bibledit Cloud which exhibit the behavious, and another link for Settngs / Resources in the Client. Both refer to different pages. It seems to happen that whenever a page has content that overflow the page height, it somehow starts to position things differently from what is expected naturally. And there can be many pages of that type.

**Comment by alerque** [comment]
This is roughly the same problem as #111, #113 and #128. Safari's idea about what layout to assign inside a flex box when no other rules are given is both different from all other browsers and not very useful. I have fixes for a couple individual pages but am trying to figure out how to catch it across the board.

**Comment by teusbenschop** [comment]
If Safari already is doing it, how serious will it not be with M$ IE...

**Comment by alerque** [comment]
I don't think we'll have a problem with IE.
1. For starters on the desktop people have a choice of browsers, and you've already been pushing Chrome only. I'm hoping to expand that so that FF and Edge aren't second class citizens, but flex layouts are not a problem for either of them.
2. Microsoft has dropped support for the really dead-beat versions of IE. They've pushed this agenda hard lately and to good effect. Anybody running older non-MS supported systems should run for the hills anyway, either to third party browsers or another OS. Anything supported with patches from Microsoft these days is going to be little trouble  for this app.
3. It isn't embedded into anything.

**Comment by teusbenschop** [comment]
Ok.
I have tested it on Edge and on Firefox. Both seem to be okay. That was about half a year ago.
