### ISSUE TITLE
Make user authentication a pluggable module

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#127]
Because I'm thinking of it again in relation to #92, here is something for the long term development roadmap that would make some deployment situations a lot nicer:

The user authentication should be made modular enough that it could be replaced. For example the team I work with all have accounts on an LDAP server that provides unified authentication across a bunch of services including ownCloud for file sharing, Mattermost for team chat, Gitlab for assorted project related code and issue tracking, mail services, etc. Currently I have to maintain a separate set of user accounts for logging into Bibledit.

If the user verification process was configurable, an internal database of users could be used as currently or a module could be written that calls out to a third party login authority. Whether this was an LDAP module or just an OpenID or Oauth, the sys admin setting up the deployment would be able to configure what kind of logins were accepted and potentially link it to another system so that accounts were maintained in one place.

**Comment by teusbenschop** [comment]
Looking at calling an LDAP server, which of a user's features would be stored on that server?
- Password hash.
- Level/Role
- Assigned Bibles.
- Write access to individual books.
- Email address.
- Privileges.

**Comment by alerque** [comment]
For starters:
- Username (foreign keyed to Bibledit user)
- Email address
- Password hash

That would be enough to get started. If fact you should be able to point BE at an existing LDAP instance with a normal user schema and use it for authentication without having to touch the schema (adding new fields, etc.).

Secondarily it could query a configurable LDAP  base to  check for group membership and consider that equivalent of privilege levels.

A third and final level would be a custom schema that kept BE specific information like access to Bibles in LDAP rather than  locally. This would enable mapping to existing team schemas, but realistically I don't think most people will have a use case for this yet.

**Comment by teusbenschop** [comment]
Thinking about how to implement the additional and optional LDAP authentication:

There should be local accounts, and accounts authenticated by the LDAP server. So a good idea seems to be to have an extra field in the users.sqlite database for whether this account is from LDAP. Does this sound sensible?

When the LDAP server no longer authenticates an existing account on Bibledit, then should that account be deleted straightaway, or should it be disabled? (There may be transient authentication failures when connecting to the LDAP server, and that should not lead to immediate deletion of the account in Bibledit).

So a good idea seems to be to have a "disabled" field in the users database, that can be used to disable the account but not throw the record for this user out. Then when an account is disabled, Bibledit should continue to poll the server, once a day or so, for whether this account is really disabled, or gets enabled again. Does this sounds sensible?

I am thinking that a good way to enable LDAP authentication is to put a text file ldap.conf or similar in the config folder.

I am also considering to log LDAP queries to the journal for the admin to view, but no others to view. This may assist the admin in setting up the LDAP connection, and for trouble shooting.

**Comment by teusbenschop** [comment]
Bibledit Cloud does not know a user's password. It stores them in hashed form.

The first time a user logs on to Bibledit Cloud, the user provides the password. It is only during that single submission that Bibledit Cloud temporarily knows the password, and it does not store it. So it is only during that single moment that Bibledit Cloud can query the OpenLDAP server.

Once OpenLDAP authenticates the account, Bibledit stores the password in hashed form, and never again will be able to check whether that account continues to be valid.

If the administrator of the LDAP server disables the account, then Bibledit has no way of verifying that.

Which means that once accounts change on the LDAP server, the change cannot propagate to Bibledit Cloud.

The above scenario is unlikely in real life.

So what is the missing link or the missing strategy?

**Comment by alerque** [comment]
> So what is the missing link or the missing strategy?

Not trying to keep even a hash of the password in BE at all. If an authentication server is enabled external to BE, it should be _required_ to check with that server to authenticate a user.

Once a user is authenticated BE would mark their session as authenticated and then keep track of them based on their active session. The session would be good for as long as the session cookie was valid and both sides liked it, but if it ever needed to be renewed the app would have to re-check with the LDAP server to authorize the user.

Invalidating existing sessions is different that disabling an account. Changing a user password or other account flags typically has no effect on users existing activity until such a time as they are required to authenticate. For many services this is for as long as a) the browser keeps the cookie and b) the server has its matching half. Kicking a user off a system typically requires disabling the account, then restarting any services they need to get off of. Some services keep sessions across service restarts and have an explicit way to flush sessions. Others even have ways to invalidate specific sessions.

**Comment by teusbenschop** [comment]
> Not trying to keep even a hash of the password in BE at all.

Thanks. OK, yes, how simple can things be - indeed this solution is safer than letting BE Cloud keep a password hash.

I'll implement it this way then.

As from today Bibledit Cloud can disable an account, and that also erases any session data for that account. That would help in case a user should be disabled on a system immediately, without letting cookies to expire at the browser's side.

**Comment by teusbenschop** [comment]
The Bibledit clients authenticate through the password hashes, not through sessions. Which means that the cloud should continue to store the password hashes, to enable clients to authenticate.

**Comment by alerque** [comment]
When a remote client authenticates against a cloud instance, doesn't it do so _as a specific user_?

**Comment by teusbenschop** [comment]
Yes, it does so as a specific user.

**Comment by teusbenschop** [comment]
Actually, thinking more about it, there is no real difference between clients and browsers when they authenticate agains the Cloud. In both cases, when a browser logs in, or when a client connects for the first time, the Cloud receives their passwords, and in both cases the Cloud should (and indeed will do so soon) verify the credentials agains the OpenLDAP server.

This is where things are similar.

Once authenticated through LDAP, the browser remains authenticated through the sessions based on the cookie the browser sends, and the clients remain authenticated through the hashed password the clients send.

So actually, things are similar.

**Comment by alerque** [comment]
BE client←→client communication should probably not happen using specific user credentials anyway. Pairing a cloud instance and one or more client instances should probably be done with an application token of some kind. An administrator would be able to generate a token from the cloud instance that would be provided as part of the paring process.

User authentication would be different. Once the BE instances were allowed to talk to each other, the clients would check with the cloud one to authenticate their users. If the cloud one says "authenticate users on your own, here are some hashes", I suppose they could login offline, but at least for my use case the cloud would say "pass me the credentials, let me run them by the LDAP server, and if valid I'll let you know and you can start a session". Once the session was validated that user wouldn't need the client to have internet access again unless they logged out.

**Comment by teusbenschop** [comment]
Running e.g.:

```
$ ldapsearch -H ldap://ldap.forumsys.com -D "uid=boyle,dc=example,dc=com" -w password -b "dc=example,dc=com" -s sub "(uid=boyle)"
```

it responds with:

```
# extended LDIF
#
# LDAPv3
# base <dc=example,dc=com> with scope subtree
# filter: (uid=boyle)
# requesting: ALL
#

# boyle, example.com
dn: uid=boyle,dc=example,dc=com
uid: boyle
userPassword:: e3NoYX1XNnBoNU1tNVB6OEdnaVVMYlBnekczN21qOWc9
objectClass: inetOrgPerson
objectClass: organizationalPerson
objectClass: person
objectClass: top
cn: Robert Boyle
sn: Boyle
mail: boyle@ldap.forumsys.com
telephoneNumber: 999-867-5309

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1

```

If all authentication should go through the LDAP server, then also the authentication of the admin works via LDAP. This means that Bibledit needs the user's role from the LDAP server's response. 

How can Bibledit get a user's role from a LDAP response?

**Comment by teusbenschop** [comment]
Here are what Oracle says are the standard attributes: https://docs.oracle.com/cd/B14099_19/idmanage.1012/b15883/schema_attrs001.htm

**Comment by teusbenschop** [comment]
It seems logical, after searching a bit, to take this one, for example:

```
memberOf: cn=Kanboard Managers,ou=Groups,dc=kanboard,dc=local
```

On parsing, Bibledit looks for text fragments, e.g. if it finds "Manager", the role will be a manager. Same for all the other roles that BE knows of. Of no membership is found, the user gets the lowest possible role, which is Guest.

**Comment by teusbenschop** [comment]
And this is what you said above:

> Secondarily it could query a configurable LDAP base to check for group membership and consider that equivalent of privilege levels.

Great minds think alike 👍
