### ISSUE TITLE
Long notes overflow link at start and end

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#128]
On Mac OSX, opening a long note in the workbench causes the top link, to edit the note's subject, and the bottom link, to add a comment to the note, to be overflowed by the note's text. This makes it hard to edit the note's subject, and makes it hard to add a comment to the note.
![screen shot 2016-04-20 at 09 26 48](https://cloud.githubusercontent.com/assets/1310167/14666497/0d3e03ca-06da-11e6-9f2b-268dfed5fa58.png)

**Comment by teusbenschop** [comment]
Adding a comment to such a long note is just entirely impossible ...
![screen shot 2016-04-20 at 09 31 23](https://cloud.githubusercontent.com/assets/1310167/14666591/b86e63f2-06da-11e6-84d9-b67dd8d214a4.png)
It is affecting our translation capability on a Mac: We cannot make notes through the native Mac app anymore.

**Comment by alerque** [comment]
Replicated, looking into it. This is roughly the same issue as the outstanding issue with the journal (#111). Page content needs to be inside a wrapper (or have whatever existing div object it produces) that is tagged in such a way it knows it's place in the flex layout scheme.
