### ISSUE TITLE
The visual chapter editor no longer scrolls the caret into view

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#132]
In a longer chapter, the visual editor used to scroll the caret into view. But it no longer does that now.

**Comment by teusbenschop** [comment]
This applies to the situation it is embedded in a desktop.

**Comment by alerque** [comment]
Did you test this before of after merging #129? I fixed a number of scroll issues there but there are so many different scenarios that code can run in need no know if I broke something with those fixes or just didn't get a scenario fixed.

**Comment by teusbenschop** [comment]
I tested it right after merging @129. It also occurs in http://localhost:8080/workbench/index?bench=4 in the default clean setup.
