### ISSUE TITLE
Visual chapter editor no longer highlights the focused verse

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#133]
The visual chapter editor used to highlight the focused verse, making it light yellow. It no longer does that now.

**Comment by alerque** [comment]
Hm. Works for me in Safari, Firefox and Chrome. I have some changes to that styling code too but they are in a branch I haven't presented for consideration yet.

**Comment by teusbenschop** [comment]
Strange... it does not work this side in Chrome.
![screen shot 2016-04-20 at 16 16 05](https://cloud.githubusercontent.com/assets/1310167/14677777/5e235202-0713-11e6-8132-dbe3a0b82db0.png)

**Comment by alerque** [comment]
Now I'm more confused. That screen shot is Chrome and it looks like it's working. Is that from before the breakage or current? Either way can you check with the inspector and see if  the `.focusedverse` class is  getting set on the span element?

**Comment by teusbenschop** [comment]
This is so weird: Due to the bright sun I had put my screen brightness at its highest level, to be able to see what's on the screen. But that high level made the yellow invisible. When turning the brightness down, the bug was fixed :)
