### ISSUE TITLE
Start-end tags mismatch at offset 477: an></p></hr></div><

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#134]
The visual verse editor at http://localhost:8080/editone/index, when it saves, the Journal gives the following message: 

```
Start-end tags mismatch at offset 477: an></p></hr></div><
```

**Comment by teusbenschop** [comment]
It edits Genesis 1:1 in the sample Bible in the sample above.

**Comment by alerque** [comment]
Is this a new thing?

**Comment by teusbenschop** [comment]
Yes, it is a new thing. Because I always check the journal carefully after work, and have not yet seen this for a very long time.

**Comment by alerque** [comment]
I can reproduce this, but so far no clues as to why…

**Comment by teusbenschop** [comment]
The tags mismatch occur with one or more footnotes. 

It was caused by feeding the XML processor with HTML, i.e. feeding it with `<hr>` rather than with `<hr` />, to start with, and in the processing train, the correctness of XML was corrupted even further.
