### ISSUE TITLE
Does not always create the dynamic stylesheets on Android

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#135]
On other platforms it always creates the dynamic stylesheets, but not so on Android. At times these stylesheets get created, at times they don't.
If they are created, this entry is visible in the Journal:

15:40:29 | Creating stylesheet.css files

If they are not created, the entry isn't there.

**Comment by teusbenschop** [comment]
This is an old bug, by the way.

**Comment by alerque** [comment]
I'm totally confused by the stylesheet generation system and layout anyway.  For example some of the code from inside the unittests directory makes its way into what the browser renders on a live install.

**Comment by teusbenschop** [comment]
1. The stylesheet generation is to be done because the user can edit the visual appearance of each USFM marker. So if the user changes the appearance, Bibledit needs to generate new .css files that have the updated appearance.
2. What is the code inside the unittests directory that makes its way into what the browser renders on a live install? I'd like to clean that up, because it is not supposed to be like that. That would be confusing indeed.

**Comment by alerque** [comment]
1.  Isn't that what the "cascading" part of CSS is about? Shouldn't this just me a matter of _saving_ the user's styles to a style sheet and having it loaded l last so it has the easiest time overriding previous values?
2. The assorted classes from `unittests/tests/editor.css` are getting applied in my browser to the visual editor. Popping open a chapter in the editor, then changing that css file and reloading the browser applies the changes I made. There might be other things going on to but that's one I noticed.

BTW you might hold off on fixing either of these issues until you have a look at and decide what you want to include from some other style sheet cleanup I did. If you do muck around with where the stylesheets are or how they are generated that will end up being a merge conflict and I'll have to redo them. It isn't a big deal to rebase later, but if this is a low priority fix I would hold off so you can do it after the already-made changes.

**Comment by teusbenschop** [comment]
I think that what you describe in items 1. is what is happening now, or at least, that is the idea of what is is supposed to do.
For item 2: That certainly is not the intended behaviour, and would need to be fixed. 
Yes, I'll hold off from fixing these two issues till an issue is submitted about it.

**Comment by teusbenschop** [comment]
One theory on why it does not always create stylesheets on Android is that the flag to do so is set in the filesystem before the folder structure to do so is available, with the result that the flag could not be set, and hence the stylesheets would not be generated.

**Comment by teusbenschop** [comment]
This theory likely is not the cause because it only triggers the stylesheet installer after the data structure has been created, judging from the code.

**Comment by teusbenschop** [comment]
This is another weird bug: On Android, it seems like it does not always run the first scheduled tasks. 

It schedules a task for creating the initial dynamic stylesheet, but it does not always run this task. 

It looks weird now, but of course, the solution could be a simple thing - just that I don't know it right now.

**Comment by teusbenschop** [comment]
Trying to delay the timer till all data structures have been installed on the device, and have been initialized. This was implemented, an Android port was created. The result is that this makes no difference. It still skips creating the dynamic stylesheets. There's no trace even of this in the Journal.

**Comment by teusbenschop** [comment]
The fix is that the library now waits till the “processes” folder is present, before scheduling a task in that folder. The fault was that it schedule a task before the folder structure to create that task was there, with the result that the task could not be stored, and consequently never ran.
