### ISSUE TITLE
Scroll position commands sent once per second

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#144]
Copied from comments on #142:

> I didn't realize that the browser is receiving scrolling commands every second, once per poll. This certainly is not happening by design. Thanks for finding the behaviour, and for the fixes in this pull request. I have merged it.

This is probably the root cause for #143 too, but the fixes may be different so I'm opening another issue to track the fix.

**Comment by teusbenschop** [comment]
I have measured the scrolling commands sent to the browser, through logging to the console, and am seeing that it only sends the scrolling commands to the browser when necessary. When the caret is stable, it does not send any scrolling command to the browser.

**Comment by alerque** [comment]
What browser were you testing in? I wonder if there is a JS bug affecting only some engines.

**Comment by teusbenschop** [comment]
I have tested it on Google Chrome for Mac, version 49.

**Comment by teusbenschop** [comment]
It occurs to me that I've seen this bug before. It kept scrolling the caret into view. And that was also on google chrome. Since it now is gone, it take it that it got fixed along the way, by accident, as it were :)
