### ISSUE TITLE
Replace text checkboxes in links with semantic ui controls

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#150]
In 5793861 I started replacing the links that were play-acting at being check boxes with real check  boxes. This will allow browsers to style them much better out of the box, but more importantly it enables them to _function_ like other user input controls on whatever platform they are on. Touch devices often have special handling of `<input>` elements that covers the edge cases of that platform.  We don't want to eschew all that. If we want custom styling we can apply it to input fields too, but we want the semantic meaning and assorted UI event handling that goes with along with actual inputs.

However I only fixed one set, there are others:
- [ ] Move the Javascript handler to somewhere as generic as possible that will be loaded on all settings pages
- [ ] Replace all remaining instances of check links (basically anywhere `get_tick_box()` sets a value that feeds into an HTML template).
- [ ] Fix the server side handler code so it actually checks the _value_ of the parameter not just the existence of a parameter.
- [ ] Change the handler to respond to AJAX calls and adjust  the Javascript function to send AJAX requests instead of reloading the page on every setting change. Request return codes should be checked and the  setting reverted if an error comes back.

See also #147 for how this came up.

**Comment by teusbenschop** [comment]
Yes, I agree that using real check boxes is the right thing to do. Just I can't remember how those links came in....

**Comment by teusbenschop** [comment]
Of course, now I remember why links were used: Clicking the link updates the setting on the server immediately. And clicking a check box just changes the state of it. Probably you found a way to save the settings.

**Comment by alerque** [comment]
> And clicking a check box just changes the state of it.

That's what the `onchange` event is for. See how I implemented it the linked commit for an example.
