### ISSUE TITLE
Local URL broken in mixed-host-name testing

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#164]
It looks like #95 is mostly resolved with the new setting for what the BE url should be. This works pretty well in the case of using it through a proxy where it doesn't know it's own hostname.

However there are two related scenarios that are now harder to setup.
1. The initial instalation may not be on `localhost` at all. In the case of remote server installs I couldn't even access the app out of the box and had to user a proxy with a header rewrite filter turned on just to reach the app.
2. In the case of local installs the instance may need to be usable on more than one URL. When a central server with a canonicals URL isn't is use different people might actually need different hostnames. For example I'm running a dev server on a local linux box where `http://localhost` works for accessing it from itself, but in order to test from other machines in the LAN I have to use it's hostname `http://machine`. In the case of accessing it from outside the LAN it even has another URL `http://machine.router.example.com`. 

The new setup works great for permanent installations and proxies, but we actually need some aspects of the old setup for these ephemeral setups. 

Both of these scenarios relate to two factors that likely both need to be tweaked:
1. The hard coded default of  `http://localhost:[port]` when no value is set.
   
   This probably needs to change to using the old host detection code when no value is set. If a value is set, _then and only then_ use the database setting to encode URLs.
2. The very first page loaded does a redirect.
   
   Redirects are certainly necessary for some situations, but the main navigation of the app including loading the start page and accessing the settings as well as basic navigation should all function without any redirects. In MVC lingo, the router component needs to handle requests for route `/` and other basic routes without passing back a redirect header at all. The app should be usable to the point of accessing the settings page to set the URL without getting sent a (possibly broken) redirect.

**Comment by teusbenschop** [comment]
It looks like running Bibledit Cloud behind a proxy is not yet ready for production use, seeing the scenarios where it runs differ rather much.

As for suggested point 1, I think that the default suggested is now to use the old host detection mechanism when no value is set for the user-facing URL, but would need to check on that to be certain.

About point 2, the first page loaded does a redirect when accessing http://site.org/ (because there's no index page at that location. It redirects to http://site.org/index/index. When accessing http://site.org/index/index straight, there won't be any redirection. That means when navigating straight to the settings page for setting the user-facing URL, it is possible to do that without any redirect.

**Comment by teusbenschop** [comment]
I am planning to move this setting in a config file in the "config" folder, which has the advantage that only the server admin can change the setting, which gives more security, and the bigger advantage is that an incorrect setting can easily be corrected, without the need to log into the Bibledit Cloud app.

**Comment by teusbenschop** [comment]
The setting has now been moved to a text-based configuration file, see commit https://github.com/teusbenschop/bibledit/commit/fc1367fd0f2fa3d37b731f6bd7a41027b3d5e6c2

**Comment by alerque** [comment]
Sounds like a good plan to me as that is hosting setup not a run time preference.

**Comment by teusbenschop** [comment]
Looking at this now, it appears to me that the text-based configuration file for the user-facing URL resolves the last issue mentioned here, and am going to close the issue. Please re-open if I am mistaken.
