### ISSUE TITLE
cannot edit desktops in Android client

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#166]
https://groups.google.com/forum/#!topic/bibledit-general/TTBi5ghhaoY

> When editing desktops, one cannot do it in the Android version unless one uses a mouse. It won't let you edit via touch.

**Comment by alerque** [comment]
Do we have a "last know working in version X" for this?

**Comment by teusbenschop** [comment]
I don't know in which version it worked last, because I always edit the desktops in the Cloud, then let the clients download the configurations. Perhaps Phil may know in which version it worked for him last. He's available via the google group (https://groups.google.com/forum/#!topic/bibledit-general/TTBi5ghhaoY)

**Comment by teusbenschop** [comment]
This was fixed in https://github.com/teusbenschop/bibledit/commit/89c5b900890212bba2347f3f0f8c264748a09eb1. It had to do with drag handlers getting in the way of touch handlers.
