### ISSUE TITLE
Phase out OpenSSL and cURL

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#177]
When the embedded TLS library is fully working, phase out OpenSSL as much as possible, and the same applies to cURL. It may be that this requires another library again to deal with mail servers for sending mail, or another way to interface with mail servers.

**Comment by teusbenschop** [comment]
Once cURL is phased out, and it uses the internal secure http GET routines, when fetching resource content, the https fetcher in Bibledit does not check the presented certificate. This is okay because the content is going to be filtered anyway, so any dangerous content will be filtered out.

**Comment by teusbenschop** [comment]
On second thoughts: mbed TLS is now used with Bibledit's home-grown http fetcher, but this http fetcher has been tested with Bibledit Cloud, and works well there. After it failed to fetch secure content from a few sources online, it becomes apparent that this http(s) fetcher is not yet ready to fetch content from all sources. So on seconds thoughts: Let cURL do the hard work of fetching content from external sources. It does that well. It's only used in the cloud editions, not on clients. And when libcurl remains, openssl as its dependency also remains.

**Comment by alerque** [comment]
I think you're probably right about this. As much as having openssl as a dependency is a pain, there isn't really a better tool for this job than cURL.
