### ISSUE TITLE
applying \add... to two adjacent word removes space between them

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#181]
This one has not been confirmed but needs to be looked into: When applying \add... to one word, then doing it also to the next word, at one occasion the space between the two words was removed.

**Comment by alerque** [comment]
As in USFM content something like:

```
This is a verse with \add two\add* \add added\add* words in a row.
```

If so is this a valid use case or should the tags be merged anyway? If it's a valid USFM format I can make sure the styling outputs something reasonable without collapsing margins between tags.

**Comment by teusbenschop** [comment]
It were better if those two sets of tags were merged into one set of tags, even if having two sets is valid USFM.
The editor keeps the margin between the tags, so that's doing fine.
After a quick look at it, there seems to be something in the conversion from html in the browser to actual USFM on the server that removes a space in such a case.
This situation of applying \add.. to two adjacent words does not occur very often, because normally a user would select the whole phrase and applies the tags in one go.

**Comment by alerque** [comment]
Is there ever a valid use case for this? I could see sequential footnote or other editorial tags, but back to back inline markup seems like it's probably broken. Can we do something like `s!\add\*\s*\add\s*! !g` on the USFM side to normalize the markup without breaking _anyone's_ content?

**Comment by teusbenschop** [comment]
The content in USFM that this case is about would look like this:

```
\add one\add* \add two\add*
```

Whether this is valid USFM, from a technical point of view, yes, it would be. I believe that Bibledit should just be able to handle this USFM fragment without removing that space between word 'one' and word 'two'.

Whether there is a valid use case for this? Yes, because today it happened during my translation work. I had marked up one word "one", then discovered that word "two" also should have the same markup, and that's when Bibledit dropped the space in between the words.

The `sed` fragment could be ran on broken USFM but perhaps so far nobody ever encountered it :) So once it's fixed in Bibledit, that it no longer throws that space away, all should be well from then on :)
