### ISSUE TITLE
Burn down chart in email malformed

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#183]
The burn down chart as it is in the email is a bit malformed:

![screen shot 2016-05-13 at 14 07 29](https://cloud.githubusercontent.com/assets/1310167/15247373/15c66a2c-1914-11e6-81e7-857225aa31fb.png)
1. The blocks are aligned vertically rather being stacked up from the bottom.
2. The word "days" used to be centred horizontally but now it is at the left side.
3. The spacing between the vertical bars is not the same for all of the bars.

**Comment by alerque** [comment]
In there an easy way to manually trigger email reports for testing purposes? It wasn't obvious to me how to get my hands on the email output to fix it.

**Comment by teusbenschop** [comment]
Yes, there is: To set the SMTP server in the Bibledit Settings, and then to create a short sprint planning, then to mail the information to the subscribers, from the sprint planning.

**Comment by teusbenschop** [comment]
Online it works properly with `<table class='burndown'>` and the email also receives the same fragment in the email. But the problem is that the email cannot find the CSS to define the class :) So I'm going to put the class definition in the email.
