### ISSUE TITLE
Bad network connection gives errors

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#184]
Reference:

https://groups.google.com/forum/#!topic/bibledit-general/Hd8IB7oh9GY

**Comment by teusbenschop** [comment]
Another reference: 
https://groups.google.com/forum/#!topic/bibledit-general/fMxKfUOURgk

**Comment by teusbenschop** [comment]
When the network is bad, or there's no network connection, there's some undesired fatal errors in the journal.

The first fatal error is always a "disk I/O error" on a database, and the subsequent errors all say "database disk image is malformed". It looks like the first IO error damages the database.

Now this looks like it is going to be a tough one to solve. Because how can a bad network connection lead to IO errors and a damaged database?

It occurs on Android, and not on Linux or OSX.

Testing on Android.
- Kill Bibledit.
- Switch network on.
- Start Bibledit.
- Select a resource to install: Abott....
- Clear the resource's cache.
- Start installing the resource.
- Notice in the journal that it is caching okay.
- Swith the network off.
- Notice in the journal that installing the resource fails gracefully.
- Kill Bibledit.
- Start Bibledit.
- Go to the Journal.
- Notice in the journal that installing the resource fails gracefully.
- Wait a minute or so.
- Press the home button.
- Bibledit will crash.
- Start Bibledit and go to the Journal.

After a while there is an entry with "disk I/O error".
And the next entries are all about "database disk image is malformed".

I am greatly puzzled.....

**Comment by teusbenschop** [comment]
It occurs with a resource named "Abbott's Illustrated New Testament". Perhaps due to the ' in the name? And it has nothing cached at all due to the malformed database image. Try to remove the ' whether it makes a difference: Another resources was installed, without any quote: It makes no difference: It has the same database errors.

**Comment by teusbenschop** [comment]
Trying to get more and specific information about the first IO error and subsequent errors. 
This was done by making a call to the extended error information of the SQLite library.
Result: It behaves the same on Android as before.
It keeps giving the "disk I/O error" as before, and no more specific information than that.
Conclusion: The extended error information does not provide the extra information we need.

**Comment by teusbenschop** [comment]
Try to put a reasonable delay in after a network call that has failed while installing a resource.
After investigation, it appears that it already has a delay of one second after a failed network call. 
Which means that this delay is not going to help.

**Comment by teusbenschop** [comment]
Trying to switch secure server off on a client configuration. The reasoning behind this is that the problems on Android started after implementing the secure server.
The secure (https) server was disabled in a client configuration.
But it does not make any difference on Android. 
The errors are just the same.

**Comment by teusbenschop** [comment]
Try to listen on 127.0.0.1 on the client, on the loopback device. This was implemented and ran on Android. It appears to fix the errors related to a refused connection in the interface. So that is great indeed. But the damaged database errors remain.

**Comment by teusbenschop** [comment]
After listening on the loopback device, the errors related to a damaged database remain. These errors are easy to reproduce:
1. Switch the network connection off on Android.
2. Start Bibledit.
3. Start installing a resource.
4. Wait a while.
Result: After failing to download about 20 verses, the database gets damaged.

**Comment by teusbenschop** [comment]
Another thing that was tried was to disable the assembler code in the mbed TLS library:

```
MBEDTLS_HAVE_ASM
MBEDTLS_AESNI_C
MBEDTLS_PADLOCK_C
```

That was compiled, an Android port created, and tested on the Android device.
The result of this is that the situation improves as follows:
When starting to install a resource, without a network connection, before disabling assembler, it started to damage the database at around Genesis 1:24. After disabling assembler, it damages the database at a later stage, now it starts damaging the database somewhere halfway in Genesis 2. Which means that this leads to an improved situation, and therefore the assembler code should be left disabled.

**Comment by teusbenschop** [comment]
When not using the Bibledit interface, i.e., when not making calls to the embedded plain http server, that is, when not making calls to the BSD sockets, crashes don't occur. As soon as starting to use the Bibledit interface, i.e., making the calls to the BSD networking sockets, the crashes occur. WEIRD!

**Comment by teusbenschop** [comment]
A new Android build was created where all sourcecode of the mbed TLS library was removed, and all calls to it, of course, were removed also, so that no mbed TLS code was compiled or linked into the app. Then a resource was installed with the internet connection off. The result was that it made no difference: Damaged databases occurred again, and crashes occurred again. The conclusion is that the mbed TLS library does not cause all of this undefined trouble. In a way, that is good, because it means that the mbed TLS library can be excluded as the cause of this, and therefore can be continued to be used for secure http connections.

**Comment by teusbenschop** [comment]
`
05-20 20:32:51.627   372   372 F DEBUG   : pid: 5461, tid: 5964, name: SimpleCacheWork  >>> org.bibledit.android <<<
05-20 20:32:51.627   372   372 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
05-20 20:32:51.673   372   372 F DEBUG   : Abort message: '[FATAL:scoped_file.cc(30)] Check failed: 0 == IGNORE_EINTR(close(fd)). : Bad file descriptor

`
There's many of the above crashes reported in Android ADB logcat, all of them refer to bad file descriptors, then Linux sending the abort signal, which crashes Bibledit.

When there's a network connection, there's no bad file descriptors. And when there's no network connection, the bad file descriptors seem to be piling up. It certainly looks like a file descriptor does not get closed when the network is not available. Whether this is a bug in the Android OS, or a bug in Bibledit itself, would need investigation.

**Comment by teusbenschop** [comment]
What is troubling is that on Android, the maximum number of open file descriptors is limited to 1024.
See http://stackoverflow.com/questions/8870174/is-stdcout-usable-in-android-ndk.
Other devices allow thousands of open file descriptors, and that's what we need. But Android is just archaic, with its 1024 file descriptors. If that were 1024 per process, that would be better, but now it is 1024 for the entire device, and that really troubles us.

**Comment by teusbenschop** [comment]
When the network was disconnected, a value of 0 was given to the socket. Then this socket would be closed, like

`close (0);`

That worked fine on Linux, and probably elsewhere also, and it worked fine on Android for a couple of such calls. But after file descriptor 0 was close-d sufficient times, there were going to be crashes on it. And file descriptor 0 is for stdin, so it was closing stdin multiple times till it crashed. So far the Android port, that no longer closes a file descriptor of 0 (stdin) runs well, without problems.

**Comment by alerque** [comment]
Huh.

**Comment by teusbenschop** [comment]
A very small thing, yet, with far-reaching implications :)
When implementing secure http, I had redone part of the network stack, and that was causing all of this. :)
But while looking into this I had prayed to God for assistance, and here He is: Giving the requested assistance :)
