### ISSUE TITLE
Resource takes two lines in Resource Organizer

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#186]
![screen shot 2016-05-17 at 08 01 17](https://cloud.githubusercontent.com/assets/1310167/15312564/983af22c-1c05-11e6-8821-7e8544b922fa.png)
See the screenshot. The LXX takes two lines, rather than the one it should take.

**Comment by alerque** [comment]
I am unable to replicate this. If my window is so narrow that the title does not fit on one line (whether that exact LXX resource or others) the title does wrap to two lines, but I do not get the extra ✗ mark in front of it as shown in your screen shot.

**Comment by teusbenschop** [comment]
After clicking both X marks to delete both lines, and then putting the LXX back, it now behaves as it should. So I fail to reproduce it also. I'll close the issue, probably this is something to keep an eye on whether it occurs again.

**Comment by teusbenschop** [comment]
I can now reproduce the behaviour as follows:
1. Drag the LXX to another location.
2. Refresh the page.
Result: The LXX is broken into two lines, and it breaks on the comma.

Theory: The dragging javascript uses commas to separate the dragged items when sending them to the server, so the server thinks the comma within the LXX full name, is a separating comma.

**Comment by teusbenschop** [comment]
After commit https://github.com/teusbenschop/bibledit/commit/1760a281ae2cc1aa35966e2bc70ac9b85daf3c04, the issue no longer can be reproduced, and can be considered to have been fixed. The theory in one of the previous comments was correct: The comma broke up the name of the resource into two. The new way or reordering no longer uses a comma or whatever at all.
