### ISSUE TITLE
Phase numerical Bible ID out in favour of Bible name

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#190]

**Comment by alerque** [comment]
Phase it out of where? The user facing interface or the data on disk structures? Having a digital ID separate from the name makes it possible to do renames without having to muck around in too many places in the data, but you don't have to show that ID to users.

**Comment by teusbenschop** [comment]
To phase it out in the internal datastructures. The Bible identifier is an old way of binding data to a Bible, but it is phased out already in most places, in favour of binding the data to a Bible name. It may be that it is already completely phased out by now, but this task was more of a reminder to just check that the phasing out is complete. Most data currently is bound to a Bible using the Bible name, and having two different ways of binding data to a Bible is confusing. Right now I am working on a "fast copy" bible routine, and I need to be sure to set the correct identifier for the copied Bible, and I was just thinking that such things are introducing errors in cases like this, so be better removed.

What it really means is that the old Bible ID was an integer, and the current one will be a string, that's all, basically, rather than having both the integer and the string, with all possible errors it may introduce.

I still have clear memories of such errors I made in the past, when the transfer of integer to string was in progress, to the point that some functions (back in the PHP days) were rewritten to accept parameters of either type integer or else type string (which PHP was able to do).
