### ISSUE TITLE
No padding in table

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#202]
In the table here: 
https://bibledit.org:8081/manage/write?user=consultant&bible=Bibledit%20Sample%20Bible
there's no padding for the "|" characters.
There are many such characters, and it looks more pleasing if there's some space at the left and at the right of the "|"'s on the page.

**Comment by alerque** [comment]
The `|` characters should be dropped entirely from this. If a table is being used for layout (which in this case the data is tabular so it makes some sense) then all we need to do is setup a table style that has padding and borders as appropriate. Mixing and matching ASCII box drawing and structured markup is the worst of both words.

Alternatively we could wrap those up a different way so the layout would be more flexible than a table. For example something like:

``` html
<ul class="book_options">
    <li><input name="{abv}_editable" type="checkbox" /> <label for"{abv}_editable">{Book name}</label></li>
</ul>
```

Then if you like, float them into rows:

``` css
ul.book_options li {
  float: left;
  width: 10em;
  list-style: none;
  padding: .2em 1em .2em .2em;
}
```

**Comment by teusbenschop** [comment]
Ah, yes, I see, your proposal sounds excellent!
(I am still thinking the old-fashioned style - but would also need to upgrade my thinking - but honestly, graphically I still have to learn a lot ...) :)

**Comment by teusbenschop** [comment]
I think there's lots of places in the app where it has `|` used as dividers between two bits of information. It is not just here in this table, but elsewhere also.

**Comment by alerque** [comment]
Yes, that's part of why I brought it up here. I've been fixing them as I come across them (for example in my remake of the menus, which I still have to touchup for submission) but there are a lot of places where the markup being messy makes styling it difficult. When bits like this do come up that need fixing anyway, that might be the best time to also refactor them.

However lets keep an eye on what parts are being repeated. I see a lot of things with hard coded output that are doing the same work as other hard coded bits. Any time that starts happening they probably need to be generalized into interface components that can not only be output with less hassle in the code but styled consistently across the board as well.

**Comment by teusbenschop** [comment]
Yes the hard-coded output is another issue that could be tackled as we're moving forward. One simple way of creating generalized interface components would be to use the included pugixml C++ library - it works really easy for setting elements and their attributes and their text content.

**Comment by teusbenschop** [comment]
And another thing that has been on my mind for years now is to update the template engine so it supports iterations - but this is a bit harder. That way one could write real html in a .html file, and the template engine would fill it with data, iterating over, say, a vector or list or map of data.

**Comment by teusbenschop** [comment]
The template engine (called Flate) now supports basic iterations over containers, see https://github.com/teusbenschop/bibledit/commit/6c253e0fbab339910692a0a7e211bb9d0e29ba0d.
