### ISSUE TITLE
Client mails user via the Cloud about merge irregularity

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#209]
When the client notices a merge failure within itself, or rather a "merge irregularity"  it schedules an email, to be synchronized to the Cloud, and this mail contains the details of the irregularity: Base / modification / prioritized modification / output.

**Comment by alerque** [comment]
Is this a feature request or a bug report?

**Comment by teusbenschop** [comment]
The wording of the issue was unclear. It is a feature request, it's the wish that a client would do that.

**Comment by teusbenschop** [comment]
A reminder for whoever implements this is that in paratext/logic.cpp there's still a need for putting the check on merge irregularity in - it was not yet done because this is a client and it cannot yet send mails.

**Comment by teusbenschop** [comment]
Another reminder: Also to put the check into sendreceive/bibles.cpp.
