### ISSUE TITLE
Investigate mercurial / Paratext sync

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#246]
Investigate whether the Cloud can receive a copy of a local Paratext installation, in particular the .hg folder, already connected to the Paratext server, and whether the Cloud can then from then on continue to keep this mercurial repository updated, and so synchronize the Bibledit Cloud with Paratext installations.

**Comment by teusbenschop** [comment]
It is possible to check the $ hg command on Linux while Paratext on Linux sends and receives, and it is possible to enter this hg command manually. But then there's a lot of configuration options to passed to hg to get it to sync, and there's a lot of security to get through. So taking all of this in account, and all problems that could arise, it is probably not yet time now to implement this.

**Comment by alerque** [comment]
There are such things as transparent bidirectional bridges to wire in mercurial repositories into git workflows. Rather than implementing mercurial support  into Bibledit I would suggest a small standalone helper ap that uses existing bridging tools and injects any additional conversion between Paratext  and Bibledit formats in the process.

**Comment by teusbenschop** [comment]
Tracing the mercurial calls when Paratext does a send and receive, there's a very long command line to access the repository, and it is secured by credentials. If the Paratext developers would provide such a stand-alone app that acts as a bridge, that would be great. I have asked a few times for access to the repository, but it was not given.

**Comment by alerque** [comment]
Wait one end of this bridge would have to be to a remote walled garden? Somehow I thought that would be local. Nevermind then I agree the time hasn't come yet to light a fire under that bridge.
