### ISSUE TITLE
Write all incoming Bible data to git

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#257]
All incoming Bible data, from online and from clients, plus the merge data, write it all to the git repository. This enables us to track merge errors more easily.

**Comment by teusbenschop** [comment]
Check that Bibledit-Gtk does not get confused because of this extra data.

**Comment by postiffm** [comment]
Hi Teus, did you make any changes to the bibledit-gtk code? We are working on it in a separate repository, and I am wondering what exactly changes you might have made. Thanks. Matt

**Comment by teusbenschop** [comment]
Hi Matt, interesting to hear you're working in a separate repository - where would that be?

As for changes in Bibledit-Gtk, no, I am not making changes in it, but just going to check that the existing Bibledit-Gtk, as it comes with Ubuntu 16.04, would work with a git repository where extra data is put into.

**Comment by postiffm** [comment]
Our working repo sits in my personal github account. We were awaiting Caleb's split of the repo and I will merge changes in when that all comes about. I don't have Ubuntu 16.04 yet. Will soon, and will check it out. --MAP

**Comment by teusbenschop** [comment]
Cool - thanks!

**Comment by teusbenschop** [comment]
Checking that Bibledit-Gtk does not get confused because of this extra data:
- Create repository.
- Connect Bibledit-Gtk to it.
- Clone it.
- Commit a mess to the repository.
- Check Bibledit-Gtk sends/receives correctly.
- Disconnect Bibledit-Gtk.
- Reconnect Bibledit-Gtk and see how it goes.

Result: Everything in Bibledit-Gtk and Bibledit continues to work fine.

On seconds thoughts, rather to write extended journal entries about the merge operations.

The advantage is that the journal entries are volatile, as there's no need to have a permanent record in git of all ins and outs of the merge operations.
