### ISSUE TITLE
Native MS Windows edition

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#268]
Currently Bibledit uses cygwin for translating unix calls to windows calls.
Update it to no longer use unix calls on windows, but to use the native windows calls instead.
Samples of how to do this are in Bibledit-Gtk.
It would help to compile under  MSYS | MinGW.

**Comment by teusbenschop** [comment]
@alerque Hi, I am now intending to look at using native MS Windows calls for the bibledit library, rather than translating the calls through the cygwin library. So I am intending to clean up the webroot folder from the windows folder, would that be okay with you? It is going to give a large change set in git, and I would not like to disturb your script for splitting the git repository. After that I would be working in the windows folder for making the move to the native calls - ThX!

**Comment by teusbenschop** [comment]
Steps:
- Compile the library, updating where it has errors.
- Probably to integrate sqlite.
- Produce a bibledit.exe which is to be started by the GUI.
- Deal with CheckWindows and try it out.
- Try out all elements of the new Windows port.
- Disable --enable-msys in configure and #ifdef's.

#ifdef HAVE_MINGW
#else
#endif

Check the changes at this mark: CheckWindows

Example network stuff in Windows:
https://github.com/teusbenschop/bibledit/blob/a6c9aa9c0c8f797cc09378d4cec60e83b014620c/gtk/src/httpd.cpp
https://github.com/teusbenschop/bibledit/tree/a6c9aa9c0c8f797cc09378d4cec60e83b014620c/gtk/windows

After successfully building it on MinGW, it gives segmentation errors which make little sense. At this point I don't know how to proceed with it.

**Comment by teusbenschop** [comment]
The new plan is to now build Bibledit for Windows through Visual Studio Community 2015.

**Comment by teusbenschop** [comment]
It was DONE 👍

**Comment by alerque** [comment]
I'm sorry I wasn't able to keep up with this for a couple months. I'll catch up and adapt. And hopefully get that split done.

**Comment by teusbenschop** [comment]
@alerque I am sure you were busy with other things - looking at your personal repository: It's full of stuff... :)
