### ISSUE TITLE
Non-editable verse in visual verse editor

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#297]
In the Visual verse editor, it is too easy to place the cursor at the beginning of a verse and use the backspace key to erase the space before the verse number or even the verse number itself. I did that inadvertently and just got an e-mail. I'm glad that Bibledit refused to save that change! But, wouldn't it be better to just protect those characters in the Visual editors?

It would seem to me that doing things like combining verses or re-splitting combined verses should only be done in the USFM chapter editor.

**Comment by teusbenschop** [comment]
Here is the code for an editable verse:

`<div contenteditable="true"><p class="p"><span class="v">12</span><span> </span><span>I thank him who enabled me, Christ Jesus our Lord, because he counted me faithful, appointing me to service;</span></p></div>
`

The feature request calls for the verse number and the space following it to be unable to be erased through the backspace key.

I am asking for help on this, because I am currently out of ideas how to accomplish that.

Setting the relevant "span" elements to be non-editable is possible, but then the whole "span" element, including all it contains, can still be deleted.

The Bibledit server could of course generate the relevant code, that's ok, but the bigger question is how that relevant code would look.

Verse 0 does not have a verse number, probably that can be left editable all of it.

**Comment by alerque** [comment]
The contenteditable area needs to not be the parent div but instead just the internal span. Nesting a disabled area in an editable area won't work right.

Or a prose-mirror (#97) schema in which the verse numbers are special elements instead of just text and have special actions associated with them.

**Comment by teusbenschop** [comment]
If prose-mirror can handle that, that would be great.

Shifting the contenteditable area to just the internal span works well. And that solves it for this example:

`<div><p class="p"><span class="v">12</span><span> </span><span contenteditable="true">I thank him who enabled me, Christ Jesus our Lord, because he counted me faithful, appointing me to service;</span></p></div>`

At times one editable verse contains more than one paragraph, and/or more than one span within a paragraph.

Here is a sample of such a paragraph, taken from Psalm 119:7:

`<div contenteditable="true"><p class="q1"><span class="v">7</span><span> </span><span>I will give thanks to <span class="nd">you</span> with uprightness of heart,</span></p><p class="q2"><span>when I learn <span class="nd">your</span> righteous judgments.</span></p><p class="q1"></p></div>`

This editable area is more complex, and I am at a loss as to how to fix this one, i.e., to make the verse non-editable and non-deletable, while keeping the remainder of the verse editable. @alerque Do you have ideas about how to get this right?

**Comment by teusbenschop** [comment]
Once a modern editor like ProseMirror or Quill is in place, the changes that the 'text-changed' event carries can be examined for finding out whether a verse number was deleted. If that was the case, it can be reverted immediately, or the change can be blocked via the API.

**Comment by teusbenschop** [comment]
In the new visual verse editor, based on the Quill library, it is easy to prevent the editor from deleting the verse number. Just examining the Delta that comes with the text changed event, then doing quill.history.undo () when the deleted text is suspicious, that's all what's needed.
