### ISSUE TITLE
integrate sqlite amalgamation

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#301]
The advantage of this is that the app can exactly set the configuration of SQLite for threaded access, and even perhaps to enable searching.

**Comment by teusbenschop** [comment]
https://github.com/teusbenschop/bibledit/commit/12a153ef480dd6515b033f0658c21e2ccab88184 - this integrates SQLite 👍

**Comment by alerque** [comment]
(Typically you wouldn't remove assignments from issues after they are closed, that meta data could be useful lated and Github will remove them from your list on closure anyway.)

**Comment by teusbenschop** [comment]
👍
