### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#303]
A lot of code still uses "workbench" in the function names. In the user interface, this is now called "desktop". This issue requests to update the function names in the code to match with the names in the interface for the user.

**Comment by alerque** [comment]
Have you considered whether "Desktop" might not be the best permanent home for this? I realize "Workbench" doesn't mean a whole lot to people any more, but I personally found "Desktop" to be confusing when first trying to figure out what was what. Obviously changing this again might not be advisable either, but if you've gotten any other feedback about Desktop being an overloaded metaphor to layer into a cloud based interface, maybe "Workspace" would be better.

**Comment by teusbenschop** [comment]
I am a non-native English speaker, and depend on others for the fine nuances of the meanings. There has not yet been feedback about this from any of the users. If "Workspace" is better, then that's fine with me also. It means that the GUI labels would have to be changed. But also the instructional video at https://www.youtube.com/watch?v=cE7_ZRMFMrs would have to be redone, uhmm..

**Comment by teusbenschop** [comment]
Asking for opinions on the forum: https://groups.google.com/forum/#!topic/bibledit-general/x3oB_ib5IkE
