### ISSUE TITLE
Linux update mail

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#307]
Phil: I really like the automatic version updates that are being sent out.
I assume all users get the update notification, right?
In the Linux one, please also put the link in to download the new install.sh.
That will make it super easy for users to update.

Teus: That suggestion is helpful, or, perhaps, rather to link to the installation steps, where it says what to do with the install.sh.

Phil: Including the steps would be great too, as a reminder.
I think that even <Name> probably gets the steps now, I hope.

**Comment by alerque** [comment]
This could be also be solved by proper packaging without the need for instructions. I thought I had an issue for this but can't find it, so #342 it is.

**Comment by teusbenschop** [comment]
👍
