### ISSUE TITLE
little easy improvements

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#311]
https://groups.google.com/forum/#!topic/bibledit-general/yuWBiskA2Oc

**Comment by alerque** [comment]
> Please consider these changes, which I think would help new members:
> - I suggest that when new 'members' and new 'translators' log in for the first time, they get the Basic Mode instead of the Advanced mode.
> - I suggest that the Personalize > Keep menu always visible     be set to On by default. That's so helpful in Basic Mode.
> - I suggest that the Basic Mode use the Visual Verse Editor by default.
