### ISSUE TITLE
Timing of regular tasks in Cloud

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#315]
Each instances runs several tasks during the night, and some during the day.
When there's multiple instances of Bibledit running on one machine, and when all heavy tasks run simultaneously, the result will be that that machine runs out of resources like memory and CPU. Therefore it is better that each instance runs its tasks at different times. 

One way of doing this is to set the timezone per instances, and to use that information to determine when it's midnight for that particular time zone. The assumption is that there's different timezones for the instances on one machine.

**Comment by alerque** [comment]
This solution seems inherently fragile. Rather than trying to hack around it, I would either implement process limits from the OS side that keep it from running out of resources in the first place or implement some sort of common queue & runner.

The other question here is what is the _reason_ for multiple instances in the first place? Testing? Or to isolate teams? In the former shouldn't devs be able to deal with the fallout of their own hackery? And in the latter case wouldn't fairly minor tweaks allow  one installation of the code to handle multiple teams?

**Comment by teusbenschop** [comment]
What the OS now does it to kill a Bibledit instance through OOM, and Bibledit itself then restarts itself nearly immediately. This way any misbehaving instance gets corrected.

One Bibledit instance can handle multiple teams, but that has not yet been tested fully, and it is expected that there may be interference between the teams. Also the SQLite databases it now uses have not been optimized for large installations of say hundreds of teams.

The multiple instances now running on a certain public server are completely isolated, and each instance runs under its own username. If there's enough memory and disk space, a server can run hundreds of teams without one team impacting another.

**Comment by teusbenschop** [comment]
Perhaps a good solution to the memory problem, that the OOP handler at times kills a bibledit process, would be that a Bibledit instance, before starting a tasks that it knows will require a lot of memory, would read from /proc/meminfo, whether there's sufficient memory available to start that task. And if the memory is not currently available, that it then postpones that task, till such time it can run. During certain times there's competition for available memory, so it kind works like each bibledit instance first queries the system to find out whether there's enough resources, rather than blindly starting a task that would eventually lead to the OOM handler to kill it.

**Comment by teusbenschop** [comment]
Tasks that know of themselves that they can need an ugly amount of memory should check for a certain amount of free memory, before proceeding. If that's not available, then the task should wait a while, and re-schedule itself.

**Comment by teusbenschop** [comment]
Here are the results of measuring memory usage of a couple of background tasks that are assumed to take significant amounts of memory:

```
28672 search_reindex_bibles
12288 search_reindex_notes
113229824 changes_modifications
10342400 checks_run
40960 export_usfm
163840 export_text_usfm_book
1396736 export_odt_book
28368896 export_esword
15486976 export_onlinebible
155648 export_quickbible
20480 sword_logic_refresh_module_list
```

Each line has the memory usage in bytes followed by the name of the routine that takes this memory.

**Comment by alerque** [comment]
Am I reading this right that the largest task here needs 128M of RAM?

**Comment by teusbenschop** [comment]
Yup - and that has the potential to kill processes - I was looking at it and measuring yesterday, to see where the leakage or whatever is, in order to fix it.

**Comment by teusbenschop** [comment]
I am not sure how reliable memory measurements are on macOS through the tools in mach/mach.h. Valgrind on Linux shows no leakage in the Bibledit code (but something in libcrypto and libcurl). So it looks the above figures in memory usage are not realistic nor real.
