### ISSUE TITLE
proposing a little change in wording for the change reporting

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#321]
Reference: https://groups.google.com/forum/#!topic/bibledit-general/ri4W4VKdfeY

**Comment by alerque** [comment]
> So instead of the bottom line on the Change Notification page saying:
> 
> ```
> 41  Paula all of them
> 2   Balazi all of them
> ```
> 
> Could it say?—
> 
> ```
> 41  Paula  drafted or edited 41 verses since 2016-10-4!
> 2   Balazi drafted or edited  2  verses since 2016-10-4!
> ```
> 
> Would it be easy (given the data that Bibledit records) for you to make the change reporting a little more specific? Could it say?—
> 
> ```
> 41  Paula  drafted  21 verses and edited 20 verses since 2016/10/4!
> 2   Balazi drafted   0  verses and edited  2  verses since 2016/10/4!
> ```

**Comment by teusbenschop** [comment]
The result is even better than what was request. 
The statistics are on a separate page. 
It keeps the statistics for one year, and can be reviewed anytime it's needed for the financial supporters or for writing in a monthly or quarterly record, or for any other purpose.
