### ISSUE TITLE
Default workbenches fail with Edge and IE on Win10

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#326]
The height of the default desktops is not correct on MS Edge and IE on Windows 10.

**Comment by teusbenschop** [comment]
![screen shot 2016-09-11 at 19 16 04](https://cloud.githubusercontent.com/assets/1310167/18419102/3a4ec2d2-7854-11e6-923c-ea78ae22c01d.png)

**Comment by alerque** [comment]
I have a Windows user coming on board next week so I'll look into this.

**Comment by teusbenschop** [comment]
Right now installing Chrome on Windows fixes everything that Edge fails to do - but even so it would be so great if Edge could manage the workbenches well.

**Comment by alerque** [comment]
Edge is a pretty capable browser (and if you knew how much of a Linux & Open Source geek I was you'd know how hard that is for me to say) and I'm sure we can make it handle this basic stuff. In fact the exercise will probably make the code more robust for everybody — as standards compliance is wont to do.

**Comment by teusbenschop** [comment]
Haha, I understand how hard it is to say that Edge is any good. I also used to speak about things like M$ Windoze and the like. But really, M$ by itself does not care for standards, it is only that they have been forced to comply, that is why they sort of comply now :). Of course it's a commercial entity, and when it's a wise business decision to comply with standard, they'll do. And when complying does not give a return on investment, they won't :)

**Comment by teusbenschop** [comment]
I had a quick look at it just now, in Edge, newest version. It may be related to the flex properties of the CSS rules. Switching some of those on and off in the DOM inspector in the developer tools made a slight difference. I have stopped looking at it now, it's a bit beyond my knowledge right now :)

**Comment by teusbenschop** [comment]
I had a look at the flexbox again, reading up on it, and tried a few things on MS Edge, but I didn't manage to get it to properly size the individual panes of the workspace.

**Comment by alerque** [comment]
What does a DOM inspector show is actually _in_ that space?

**Comment by teusbenschop** [comment]
Here is a screenshot. Inspecting the red spot in the screenshot opens the DOM explorer as displayed.

![screen shot 2016-12-28 at 09 06 36](https://cloud.githubusercontent.com/assets/1310167/21517193/3e6c8f2e-ccdd-11e6-8b3c-07fce66ee7a8.png)

It is the `<div class="iframewrapper">` that is there and fills the empty space.

**Comment by alerque** [comment]
I just got my hands on somebody's Windows machine for a few minutes and tried this out. I pulled up some Workspaces and they seemed to layout fine. What exactly should I be testing for? Is this only on the default workspaces (mine were customized)?

**Comment by teusbenschop** [comment]
Opening this link (https://bibledit.org:8081/workspace/index?bench=5) on for example Google Chrome, works okay, and opening it from Edge on Windows 10 results in a lot of unused empty space in the browser.


Here's the good layout on Chrome:

![screen shot 2017-01-10 at 08 45 08](https://cloud.githubusercontent.com/assets/1310167/21797772/4a02f7d6-d711-11e6-9455-35cbb7f033c7.png)


And here's the bad layout on Edge:

![screen shot 2017-01-10 at 08 45 52](https://cloud.githubusercontent.com/assets/1310167/21797778/51c0333a-d711-11e6-88ac-3a15c15ecc75.png)

**Comment by teusbenschop** [comment]
I tried changing from 

```
<div class="iframewrapper" style="flex-grow: 1">
<iframe sandbox="allow-forms allow-pointer-lock allow-same-origin allow-scripts" src="/editone/index?topbar=0" style="flex-grow: 1"></iframe>
</div>
<div class="iframewrapper" style="flex-grow: 3">
<iframe sandbox="allow-forms allow-pointer-lock allow-same-origin allow-scripts" src="/resource/index?topbar=0" style="flex-grow: 1"></iframe>
</div>
```

to 

```
<div class="iframewrapper">
<iframe sandbox="allow-forms allow-pointer-lock allow-same-origin allow-scripts" src="/editone/index?topbar=0"></iframe>
</div>
<div class="iframewrapper">
<iframe sandbox="allow-forms allow-pointer-lock allow-same-origin allow-scripts" src="/resource/index?topbar=0"></iframe>
</div>
```

but that did not resolve the issue in Microsoft Edge

**Comment by teusbenschop** [comment]
It looks like this needs the eye of an expert. 

I guessed that it might be related to the flexboxes used in the workspaces, but even that might not be true.

**Comment by teusbenschop** [comment]
The website https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ provides free virtual machines with Windows and Microsoft Edge for trying things out.

**Comment by alerque** [comment]
Thanks! I did not know about that and was dreading having to go find a Windows CD or pirate a copy to setup a box to test this. I'm setting an image to download tonight for this purpose.

**Comment by teusbenschop** [comment]
Thanks man! Good luck!

**Comment by teusbenschop** [comment]
Would it not help, in this case, to drop the idea of flexible boxes?

When suggesting this, I admit that I don't fully understand the concept of flexible boxes in html 5, but perhaps Edge also does not fully support that concept.

While fiddling with 'flex' properties in Windows Edge, it seems to affect the layout, but I never managed to make the layout in Edge such as it was supposed to be, and as can be seen on the WebKit-based browsers.

**Comment by teusbenschop** [comment]
http://stackoverflow.com/questions/33270525/expanding-iframe-within-flexbox: Solution provided didn't work.

http://stackoverflow.com/questions/34095170/edge-doesnt-stretch-iframe-in-a-flexbox: This speaks about the issue.

http://stackoverflow.com/questions/34102990/iframe-vs-div-in-absolute-positioning: This speaks about the issue. The solution is simple.
