### ISSUE TITLE
Journal does not display added records on Edge

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#327]
On MS Edge the journal does not show added records. It normally scrolls down to always display added records, but does not do this on Edge.

**Comment by alerque** [comment]
This is going to be something on [line 40 or 41 of index.js](https://github.com/teusbenschop/bibledit/blob/master/lib/journal/index.js#L40).

**Comment by teusbenschop** [comment]
Today's version works fine.

Bibledit 1.0.602

![screen shot 2016-10-29 at 13 51 42](https://cloud.githubusercontent.com/assets/1310167/19829366/dee658e6-9dde-11e6-9ddf-a3bf9ac5850f.png)
