### ISSUE TITLE
digitally sign the .exe files to avoid warnings at installation time

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#330]

**Comment by teusbenschop** [comment]
https://www.globalsign.com/en/code-signing-certificate/ - From 175 €/year: I prefer a free certificate.

**Comment by teusbenschop** [comment]
Not sure if the price of the certificate is worth it.

**Comment by alerque** [comment]
I've heard of ways to get  free signing for Open Source projects, but I'm not sure how much trouble it is and whether the frequent update cycle would be inhibited. This is one of those places where the Windows software world doesn't play very nice outside of a corporate mindset.

**Comment by teusbenschop** [comment]
I would be interested in a way to get free signing for open source projects, that works on Microsoft Windows.

As for the frequent update cycle, isn't it so that once they issue a free private key, for signing the .exe, that this key can be used as often as the developer wants, without troubling the issuer?

**Comment by alerque** [comment]
I'm not sure if the thing I saw was an issued key or a way to trigger a build of a public repo and have them sign it. It seems like I've seen both types of things (the former obviously being preferable) but at the time I was looking for a different purpose and I don't have links handy.

**Comment by alerque** [comment]
I'm going to assign myself to this to review my research. If it turns out there's nothing I'll close it again.

**Comment by teusbenschop** [comment]
👍

**Comment by teusbenschop** [comment]
Information about how often the Windows exe is used would help deciding whether it's worth the effort to spend time or money on this. I am going to look into whether download statistics on the website are possible without putting a load on the VPS running the website.

**Comment by teusbenschop** [comment]
Thread: https://groups.google.com/forum/#!topic/bibledit-general/Eam42WfpX5A
