### ISSUE TITLE
Windows app restarts at midnight

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#332]
The Windows app behaves as a server, by restarting itself at midnight. It should continue to run.

**Comment by alerque** [comment]
The server version shouldn't need to restart itself at midnight ;-)

**Comment by teusbenschop** [comment]
In theory it indeed shouldn't, and I am checking on memory leaks regularly, and there were none last time I checked. However, due to other libraries it uses, it just does not feel right to leave the binary running for years in a row. I am fairly sure that at times memory leaks would occur, or hanging BSD sockets, or another shortage of file descriptors, or whatever else one can think of where reality proves theory to be just what it is: A theory. :)
