### ISSUE TITLE
Move the code of all ports into their own repositories

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#340]

**Comment by teusbenschop** [comment]
I ran into this link: http://stackoverflow.com/questions/359424/detach-move-subdirectory-into-separate-git-repository/17864475#17864475. Posting it here for reference.

**Comment by alerque** [comment]
Code for doing this is in my branch already. Splitting the repo is easy enough, getting everything to compile after that is trickier.

**Comment by teusbenschop** [comment]
If the splitting is easy for you, that's great. Getting everything to compile is the easy part for me to do. I you do the splitting, I'll do the compiling :)

**Comment by teusbenschop** [comment]
It may need clarification why it is so easy to get it to compile after splitting the repository. Currently I compile everything in /tmp. So it's a two-steps process: 1. Copy the core to /tmp. 2. Copy the port to /tmp. Run a script that fixes everything and makes it compile in /tmp/ :)

**Comment by teusbenschop** [comment]
@alerque  I moved 'android' to its independent repository. 

That was done as I had to attend to a few issues in the Android port. So I thought that while attending to that, let's move the folders to the new location at the same time.

I realize that the history from the old repository was not moved yet, and know that you've got scripts in your repository to move the history as well.

**Comment by teusbenschop** [comment]
This feature request has been open since 28 September 2016, and a lot of work has been done on it already, but there's no progress currently. I am intending to close it on 20 April 2017 unless there's activity related to it.

**Comment by alerque** [comment]
My next stint to work on Bible software starts the 2nd week of May. Please leave this assigned to me.

**Comment by teusbenschop** [comment]
Okay!

**Comment by teusbenschop** [comment]
This issue was moved to bibledit/cloud#16
