### ISSUE TITLE
Create Linux packages for common distros

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#342]
- [ ] Archlinux
- [x] Debian / Ubuntu
- [ ] Fedora

**Comment by teusbenschop** [comment]
👍

**Comment by LAfricain** [comment]
:+1:

**Comment by teusbenschop** [comment]
Is it easy or hard to create such packages?

Where to host them: In each distro's own package server? Or on bibledit.org?

**Comment by alerque** [comment]
Arch will be in the AUR, fedora in Copr, Ubuntu on Launchpad.

It _would_ be easy to make packages if the build and install system was sane to start  with, but as it stands its a nightmare. The first step is to rewrite the process so that normal tools like `configure`, `make`, and `make install` do their jobs. The per-user scripted install that does things like makes symlinks, tries to auto-update, mucks with cron, sets up data directories, etc. is all quite unorthodox and has to go in favor of the way normal software works: install binaries to the system, shared resources to shared places, and per-user data and setup created at runtime.

After that packaging is easy.

**Comment by LAfricain** [comment]
For Ubuntu you know already no? Just add the sources on launchpad as you did with bibledit-gtk?

**Comment by alerque** [comment]
@LAfricain If there was an install routine using autoconf tools, make, etc was in place, then yes it  would be just a matter of pointing Laundpad at the sources. As it is nothing would end up in the right place and the packager wouldn't know how to bundle it up or what went where on installation.

**Comment by teusbenschop** [comment]
Yup I agree that the current architecture of Bibledit differs a lot from what is expected in the Linux world. 

One of the reasons for the current situation is that it proved to be so hard, in the past, to become a Debian developer, and thus to be able to push packages to the Debian system (and to Ubuntu and other Debian derivatives) that I got frustrated with that system, and rather used the current system, which has the advantage that it works on any Linux distro regardless of how hard it will be to become a god who has graciously received the huge privileges and mercies and benefits bestowed om him to be able to publish packages to the official channels.

**Comment by LAfricain** [comment]
Are sure that it's the same "politic" with Ubuntu (compared with debian)?

**Comment by alerque** [comment]
It's not.

**Comment by LAfricain** [comment]
Ah ok.

**Comment by teusbenschop** [comment]
Yup Ubuntu is much easier. I had intended originally to only publish to Debian, since then it would automatically go into the next release of Ubuntu and other Debian-derivatives. But that plan didn't work out :) Then I dropped all tools :)

**Comment by teusbenschop** [comment]
A way to install Bibledit in its current form would be through a Bibledit Installer. This installer would be built in conformance to standard Linux apps, and would be installable from package (still to be created). The app would be small and standard-compliant. Upon running it, the app would look whether Bibledit, in its current form, is installed, and if not installs it, and optionally would upgrade it to the latest version. So I think the yeast of this matter is that it's very easy to make a small app that conforms to all Linux standard, and create packages of it.

Any thoughts on this?

**Comment by alerque** [comment]
> Any thoughts on this?

All the worst of both words.

Also specifically prohibited by some distro packaging standards.

**Comment by teusbenschop** [comment]
If it is the worst of both worlds, still it is a pragmatic thing to do, and it gives the user more smooth experience than now, when the user has to run a shell script :) 

Adobe does that too, with their flash installer.

If some distro packaging standards prohibit this type of installer, then they lose out. :)

**Comment by teusbenschop** [comment]
For the Linux app, once the autotools install things in their canonical places, best would be to continue to use `~/bibledit` for per-user data rather than something like `~/.bibledit` (with the `.`). This has the advantage that one can easily upgrade an installation installed by the current `install.sh` to a new installation installed from canonical packages.

**Comment by teusbenschop** [comment]
The Bibledit Linux source has now been redone. 
The following tools do their expected jobs: 
```
./configure
make
make install
```
So the basis for Linux packages is now there :)

Hallelujah!

**Comment by teusbenschop** [comment]
To satisfy Debian policy, copyright statements are now being added to, among others, the CSS files in the css folder. There's a lot of work from you, @alerque, in the CSS files. I prefer to state your name and year also in the CSS files. Is this okay? If it's okay, what's the name and year(s) to be put in that copyright statement?

**Comment by teusbenschop** [comment]
There's now packages for Ubuntu.
More information about how to use them is at https://bibledit.org:8081/help/installation.

**Comment by teusbenschop** [comment]
The Debian package is ready too.
https://mentors.debian.net/package/bibledit
A sponsor is needed to upload it to the Debian archives.

There's a few overridden lintian warnings. It's about the minified JavaScript files. A possible fix would be to use minified stuff, but to change, for Debian only, all .min.js files to their full counterparts, and then to remove the *.min.js files.

**Comment by teusbenschop** [comment]
This issue was opened on 29 September last year, and packages for Debian and for Ubuntu have been created. Anyone offering to do packages for other distros? If there's no offers for this by 22 April, this feature request is considered to be complete and will be closed.

**Comment by alerque** [comment]
I'm going to make Archlinux packages at the very least. Fedora should be easy once both Arch and Ubuntu are in place (the requirements are somewhere in-between the two).

My next stint to work on Bible software starts the 2nd week of May.

**Comment by teusbenschop** [comment]
Okay, thanks man!

If it helps for creating Fedora packages, the Ubuntu packages are here: https://launchpad.net/~teusbenschop/+archive/ubuntu/bibledit

And the Debian packages are here: https://tracker.debian.org/pkg/bibledit

**Comment by teusbenschop** [comment]
This issue was moved to bibledit/cloud#15
