### ISSUE TITLE
Move teusbenschop/bibledit to bibledit/bibledit

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#344]
The existing repository housed at https://github.com/teusbenschop/bibledit can be moved (any time?) to https://github.com/bibledit/bibledit. This is a separate step from updating what's in it because we want Github to migrate all the issues and also add URL rewrites from its old location to catch traffic that has it bookmarked. Later the repository contents can be replaced with the trimmed down master repo that is basically a place holder for the platform specific repositories as submodules for the convenience of developers working on the whole system.

The existing issue tracker will become the canonical place for to track issues across the project. The current version of the repository will be archived on a separate branch in case it's ever needed.

**Comment by teusbenschop** [comment]
The transfer has been done.
