### ISSUE TITLE
Add Gitter (or other) team chat

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#345]
First of all, thanks a million @teusbenschop for tracking development activity in issues even when it seems like you're talking to yourself. I just read through 140 of them and you saved me literally days of time poking through history and mailing lists trying to get up to speed again. Speaking of mailing lists, they are great for some things, but sometimes a little more real time (but still asynchronous) would be nice. I'm particularly thinking about for developers here.

I  suggest adding a [Gitter chat](http://gitter.im/) room for this repository. This might make it easier to polish off the last few details of the repository split and maybe for other things as they come up. Since Gitter rooms are tied to Github repository paths I suggest waiting until after moving this repository into the organization namespace (see #344).

A Slack channel would be another alternative, although I think at least my expected usage is developers the integration with Github accounts in Gitter would be a good match.

**Comment by teusbenschop** [comment]
👍  The transfer to https://github.com/bibledit/bibledit is now complete, please feel free to add the chat room.

**Comment by teusbenschop** [comment]
It is operational at https://gitter.im/bibledit/Lobby.
