### ISSUE TITLE
All client ports to set their time zone

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#347]
The Bibledit library works with time zones. All client ports, as far as they can obtain their own time zone from the operating system, should pass that on to the Bibledit library. This will cause the Journal to display the correct local time.

**Comment by alerque** [comment]
How long do most people's journals end up getting? One common technique to deal with this is have the server spit out markup in UTC with the date fields tagged with the data in an easy to parse format, then have Javascript on the client side display it in the user's time zone (or not per their user preferences). This is how many timestamp things on the web handle "1 second ago" changing to "1 minute ago", "1 day ago", and eventually "January 16th" on the user end without having to have the server spit out new content every time. In fact the markup the server spits out never changes and can be edge-cached in CDNs from the first second.

Obviously worrying about CDNs isn't a factor for the Journal, and likely neither is user friendly relative time stamps, but just getting in the habit of making the server think in UTC and only displaying something else when the client knows about the offset might not be a bad idea.

**Comment by teusbenschop** [comment]
On the low power devices it is 200 entries, and on the high power devices it is 2000 entries. I do like the idea you propose to let the browser convert UTC times to local times. 👍

**Comment by alerque** [comment]
That number of entries is pretty reasonable to parse client side. The biggest trick is adding an easy to parse timestamp such as a unix epoch second counter in UTC time as a data attribute on a span around the date so that it a) shows a usable UTC time if the client site JS doesn't run (or has no time zone date to use), but making it lightweight to parse and write out a localized time in the placeholder.

**Comment by teusbenschop** [comment]
This looks like it is the way forward to go.

If the client site does not run javascript, I'd say that it then does not need to parse any journal, because the whole Bibledit app uses javascript a lot, such that if the client does not run javascript, it won't run Bibledit at all :)
