### ISSUE TITLE
Bulk data entry keystrokes

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#349]
When typing up existing content, moving from one verse to the next is way too brittle and takes too much interaction.

Using the `editone/index` editor, <kbd>ALT</kbd>+<kbd>Down</kbd> focuses the next verse, but the cursor is not at a useful place. For moving to blank verses it is somewhere in never never land and getting it back requires mouse input.

**Comment by alerque** [comment]
This issue manifests differently in different browsers, but all of them have one issue or another.

**Comment by teusbenschop** [comment]
As for the caret not being in the right place: Here's a screenshot of that.
![screen shot 2016-11-04 at 13 53 04](https://cloud.githubusercontent.com/assets/1310167/20006064/22b73afc-a296-11e6-9328-970f8cc3178b.png)

Placing the caret at a certain offset within the editable area is done through the Rangy library (https://github.com/timdown/rangy). But this library does not behave in a stable manner, therefore when making it to set the caret right at the start of the verse, it does not consistently place it there at all times, depending on the type of the browser, and also depending at the size of the text block.

So this is not something that can be fixed without a fix in the Rangy library, or else, and that would be better, implementing the ProseMirror editor, see issue #97.

**Comment by teusbenschop** [comment]
No matter what Rangy does, it has been fixed now, at least, in Chrome. I have not yet checked other browsers.
