### ISSUE TITLE
Image resources spanning multiple verses need to not reload

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#350]
For resources that are truly verse by verse, it makes some sense to reload the resources on every navigation event. But as in the case of some image resources that span multiple bits (or just in the case of skipping around in a chapter fixing small things) it gets really annoying to have the resourced blink and loose the scroll position.

**Comment by teusbenschop** [comment]
Some possible improvement would be (in the far future :) ) - to let the resource reloader kind of know if a resource spans a number of verses. Then if the new focused verse falls within that range of verses, that it then automatically does not reload that resource.

**Comment by alerque** [comment]
That would definitely be an improvement. I toyed  with automating some image manipulation to split all my resources by verse, but I think the outcome would still be clumsy for use in raw data entry situations which is where this need is coming from anyway. A chapter by chapter workflow works much better.

The image resources already know they span a verse range and pull up the right image block, but disabling the refresh for moves inside the same block would be much easier to use than the manual freeze/unfreeze. I don't know what it would do about the _other_ resources that might be show though. Refreshing them would cause unwanted scroll jumping as well.

**Comment by teusbenschop** [comment]
One possible way of fixing the issue that reloading the other resources would cause, scrolling and/or jumping, would possible be to not clear the element before loading the new element content for a particular resources, but rather to leave the old resource content in the element, then start loading the new content, and as soon as it has been fetched, to only then replace the old content with the new content. There would be a very short time that the element would be empty, but it is well  possible that this would not be visible or cause jumping or scrolling.

**Comment by teusbenschop** [comment]
(I pressed the wrong button, which closed the issue)

**Comment by teusbenschop** [comment]
It was relatively easy to fix this: Fetch the new content for the image resource, compare it with the existing content already on the page, and only reload if there's a difference.

The freeze link, that was there as a quick fix, has been removed.

**Comment by alerque** [comment]
This sounded good on paper but it doesn't work. My team is back at it for a stint and got two verses in and now I have a mutiny on my hands. The resources are jumping around (vertical scroll jitter) every few seconds and completely reloading every couple sentences.

I'm going to remove this commit from my production build to get through the day, but I'm also re-opening this issue because it needs to be revisited.

**Comment by teusbenschop** [comment]
Hmm, something is going on, the idea sounded ok, but it does not work in your case, I've to look into how to get this going. It worked when I tested it but I suspect that I didn't test the configuration or combination of resources that your team uses. Is is one image resource they're loading, or is more than that?

**Comment by alerque** [comment]
One image resource. However each image spans a range of verses and sometimes there is more than one entry that covers the same verse in it's range.

**Comment by teusbenschop** [comment]
Perhaps the loading ![loading](https://cloud.githubusercontent.com/assets/1310167/20427275/7508631a-ad83-11e6-9211-e46607f1028e.gif) icon that is made visible at each new verse is causing the jitter. If it were floating, it might be better.

**Comment by alerque** [comment]
That's a likely explanation for the jitter. That doesn't explain the scroll getting reset to the top, but it's likely part of the problem.

**Comment by teusbenschop** [comment]
What is the browser that shows the jitter? I have tested it in Chrome, but not in any other browser.

**Comment by alerque** [comment]
Firefox 49 here.

**Comment by teusbenschop** [comment]
A new fix was made that now really fixes the remaining jitter. There was jitter in Safari before this fix, and the jitter was completely gone after the fix. 100% satisfaction guaranteed!
