### ISSUE TITLE
ALT based keybindings frequently conflict with the browser

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#352]
I think the <kbd>Alt</kbd> based key bindings need to be reviewed across the board. It frequently conflicts with the browser UI.

In Firefox the default UI configuration does  not have a menu bar, but hitting <kbd>Alt</kbd> enabales it. If the focus is just right in BE and the <kbd>Alt</kbd>+<kbd>Down</kbd> command is issued fast enough it works, but if the user isn't in the right place to start with or hesitates they end up with a menu and their input focus doesn't go back where it came from etc.

In Chrome <kbd>Alt</kbd>+<kbd>Down</kbd> pulls down a history window. If BE traps it just right it works, but sometimes the user ends up navigating away to another site and can't figure out how they got there.

I would suggest <kbd>Ctrl</kbd> based sequences for in-app navigation as being the least likely to conflict, but keep away from the standard ones such as <kbd>C</kbd>, <kbd>P</kbd>, <kbd>X</kbd>, <kbd>B</kbd>, and <kbd>I</kbd> that people are used to using in word processors.

**Comment by teusbenschop** [comment]
The Ctrl-based sequences like Ctrl-Downarrow on the Mac switch between the window views there. The issue on Firefox on Ubuntu could be reproduced. Preventing the default behaviour of Alt in javascript worked reasonably well. The menu of Firefox still becomes visible while Alt is pressed down, but it does not do more than that, and when Alt is released, the menu goes away.
