### ISSUE TITLE
Sync to git repo clobbers any incoming changes

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#353]
The sync to a remote git repo is currently not functioning bidirectionally. It sends and receives alright, but _any_ new commits pushed to the remote end up being completely obliterated by Bibledit. It seems to pull down the  new commits on send/receive, but then it drops whatever data it had locally before the new commits back on top of the repository and commits it as "changes made in bibledit" and pushes that back out to the remote, effectively doing what a `git revert` would have done against anything done to the remote repo.

**Comment by teusbenschop** [comment]
Our team is using this system and has been using that for several years, with changes coming in on a daily basis and being accepted by Bibledit, and not rejecting them.

In the situation that you have, does the Bibledit journal give any clues as to what's going on?

**Comment by alerque** [comment]
Not really, unless this means something more to you than it does to me:

```
4 October 2016 20:09:02 | Has been sending and receiving during the past hour
4 October 2016 20:10:03 | Send/receive Bible Türkçe Standart Versiyon
4 October 2016 20:10:03 | receive: Genesis/31/data | 66 ++++++++++++++++++++++++-------------------------
4 October 2016 20:10:03 | receive: Genesis/32/data | 50 ++++++++++++++++++-------------------
4 October 2016 20:10:03 | receive: Genesis/33/data | 30 +++++++++++------------
4 October 2016 20:10:03 | receive: Genesis/34/data | 48 ++++++++++++++++++------------------
4 October 2016 20:10:03 | receive: Genesis/35/data | 48 ++++++++++++++++++------------------
4 October 2016 20:10:03 | receive: Genesis/36/data | 76 ++++++++++++++++++++++++++++-----------------------------
4 October 2016 20:10:03 | receive: Genesis/37/data | 58 +++++++++++++++++++++----------------------
4 October 2016 20:10:03 | receive: Genesis/38/data | 38 ++++++++++++++---------------
4 October 2016 20:10:03 | receive: Genesis/39/data | 38 ++++++++++++++---------------
4 October 2016 20:10:03 | receive: Genesis/40/data | 36 +++++++++++++--------------
4 October 2016 20:10:03 | receive: Genesis/41/data | 62 +++++++++++++++++++++++-----------------------
4 October 2016 20:10:03 | receive: Genesis/42/data | 60 ++++++++++++++++++++++-----------------------
4 October 2016 20:10:03 | receive: Genesis/43/data | 50 ++++++++++++++++++-------------------
4 October 2016 20:10:03 | receive: Genesis/44/data | 14 +++++------
4 October 2016 20:10:03 | receive: 14 files changed, 337 insertions(+), 337 deletions(-)
4 October 2016 20:10:04 | Ready sending and receiving Bible Türkçe Standart Versiyon
4 October 2016 20:15:03 | Send/receive Bible Türkçe Standart Versiyon
4 October 2016 20:15:03 | modified: Genesis/31/data
4 October 2016 20:15:03 | modified: Genesis/32/data
4 October 2016 20:15:03 | modified: Genesis/33/data
4 October 2016 20:15:03 | modified: Genesis/34/data
4 October 2016 20:15:03 | modified: Genesis/35/data
4 October 2016 20:15:03 | modified: Genesis/36/data
4 October 2016 20:15:03 | modified: Genesis/37/data
4 October 2016 20:15:03 | modified: Genesis/38/data
4 October 2016 20:15:03 | modified: Genesis/39/data
4 October 2016 20:15:03 | modified: Genesis/40/data
4 October 2016 20:15:03 | modified: Genesis/41/data
4 October 2016 20:15:03 | modified: Genesis/42/data
4 October 2016 20:15:03 | modified: Genesis/43/data
4 October 2016 20:15:03 | modified: Genesis/44/data
4 October 2016 20:15:05 | send: To gitlab.alerque.com:tsv/bibledit.git
4 October 2016 20:15:05 | send: ac79f46..205f5a6 master -> master
4 October 2016 20:15:05 | Ready sending and receiving Bible Türkçe Standart Versiyon
```

Nobody had been active in Bibledit for at least an hour and a half before I pushed commits that cleaned up stuff in 31-44 to the repo. A couple minutes later BE had pushed back a commit that reverted everything I just sent.

From the git site the history looks something like this:

![selection_253](https://cloud.githubusercontent.com/assets/173595/19087011/270afb5a-8a79-11e6-9697-cb94716d0817.png)

The top edit (`205f5a6a`) clobbered everything in the previous two (`ac79f468`and `bb769612`) that I had pushed to the git server manually. Everything prior to that had come across in automatic 5 minute syncs from BE edit activity earlier in the day.

**Comment by teusbenschop** [comment]
If it is reverting stuff, that is rather serious. Trying to think hard about what could be going on, there's nothing that comes to mind now what could be causing it.

It would be helpful to be kind of able to "replay" the situation, and I would gladly assist with that, if there's any data available, USFM data, prior to the commits, what Bibledit had itself, and after the commits.

I remember there have been issues in the past with empty verses, that were not playing well when committing them to git, and after replaying the offending bits, the code could be updated to better deal with empty verses.

**Comment by alerque** [comment]
I don't think this is an empty verse issue because all of the verses touched already existed. Basically the two commits were a search and replace to convert plain quotes as input to proper typographic quotes and to convert `YAHVE`  to `\nd Yahve\nd*`.

On the other hand this seems to be fairly reproducible. It's happened multiple times  now and the only way I found to pull in these commits to BE is to drop the sync, re-add it, and choose to use the remote data.

If you email me [a password hash](https://iguana.alerque.com/slappasswd.html) I can get you access to the git repos.

**Comment by teusbenschop** [comment]
Sent...

**Comment by teusbenschop** [comment]
Whoops, how could I ever have forgotten about this:

The ChangeLog says:

No longer reads Bible data from the git repository by default.

And file config/config.txt says:

Bibledit Cloud can send the Bible text plus changes to a git repository.
Normally the direction of this traffic is one-way.
It sends changes in Bibledit Cloud to the git repository.
Bibledit Cloud does not receive changes from the git repository.
It is possible to make a manual setting to enable it to receive changes as well.
$ cd databases/config/general
$ echo 1 > read-from-git
When enabled, the mechanism is subject to race condition in rare circumstances, and will at time revert some changes made by users.
There is no intention to fix this behaviour, because receiving changes from a git repository is going to be phased out soon.

So: The conclusion is that the behaviour described in this issue is by design...

**Comment by alerque** [comment]
Thanks for the info. I missed that in the changelog.

I'm fine with setting a flag to enable this but just so you know: I'm not fine with the feature being deprecated and being phased out entirely. This is —singularly— _the_ reason I settled on Bibledit for our translation projects in the first place and hence the reason I'm investing some time in improving it. Working directly from USFM using a git workflow into which I could inject other tooling was the main thing I was looking for.

**Comment by teusbenschop** [comment]
Okay, thanks for the update. The 'phasing out' had not yet started, but I wonder, if git is so desired, whether it not better to have 'receive from git' on by default? And then of course remove the info from that config/config.txt making git look old :)

**Comment by alerque** [comment]
What is the "rare race condition" that was a concern here in the first place? Can we assume anybody crazy enough to be mucking around in the git repo behind BE's back are also capable of finding and fixing issues in the repo itself? If I know what the problem case there might be another solution besides blocking two way sync.

**Comment by teusbenschop** [comment]
The issue was, if I remember well, that members of a translation team were sending data from their clients to the Cloud through a substandard internet connection, of such a quality that a member said she could not even post something on facebook. Bibledit Client / Cloud tried their best to make the best of it to get the data in the Cloud without corruption, and that that time at times some changes were reverted by, what I thought, was the repository itself, and I thought the quickest thing to do only write to the repository but no longer read from it. That's when this one-way thing came in. But if I remember well again, the issue appeared to be something else, and this one-way thing was kind of forgotten...
