### ISSUE TITLE
Communication between iframes and tabs

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#354]
Currently there's some communication between iframes and/or tabs that now runs via the server, but there's an easier way of doing that, leaving out the server entirely, see for example http://stackoverflow.com/questions/16657399/communication-between-iframes. It may be helpful to replace the current communication via the server with another type of communication that works more directly.

**Comment by alerque** [comment]
Just FYI, its not just tabs. I still have cross talk between different computers when logged in as the same user (i.e. cookie sessions are not being fully respected).

An easy test is  to open Chrome in normal mode + an incognito window, login to both, and navigate in one of them and see if the other jumps.

**Comment by teusbenschop** [comment]
This is what the current design of the system does. One browser, for example, sends the focused passage to the server, and the server stores it for that particular user. When the same user logs in, from the same or another browser or in incognito mode or from another tab, that user receives the focused passage from the server.
