### ISSUE TITLE
Static preview pane

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#356]
The preview pane attached to the editor views (`edit/preview`) is a useful thing to have in a workspace pane. The problem with the current implementation is that it times out and reverts to being an editor rather than staying put as a preview. A URL we could use just for preview mode with no editor controls to be messed up by clicking around in the text would be a useful addition.

**Comment by teusbenschop** [comment]
Implementation proposal:

- [x] Pass query on URL to enable the time-out.
- [x] Add jQuery that queries the chapter ID.
- [x] jQuery reloads the URL of the preview after chapter update.
- [x] Scroll the active verse of the preview into view at each navigation event.
