### ISSUE TITLE
macOS app rejected by Apple App Store

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#383]
Apple said:

> We noticed an issue in your app that contributes to a lower quality user experience than Apple users expect: Specifically, when expanding the main window, the UI gets cutoff (see screenshots 1,2). Please evaluate whether you can improve the user experience and resubmit your app for review.

Comment: When maximizing the macOS app's window, it should signal the changed screen size to the embedded browser.

**Comment by alerque** [comment]
Is this a problem anywhere other than the embedded MacOS browser widget? This might actually be a bug in that widget not triggering a re-paint of the viewport based on CSS rules after being resized. I don't think we care about getting a javascript resize signal emitted or not, this is entirely left up to CSS rendering in the widget and it should know when it needs to repaint.

**Comment by teusbenschop** [comment]
I am not aware of this problem anywhere else than in the embedded macOS browser widget.

Yes, it could be the bug that you mention. That needs a bit of investigation.

Other options that come to mind:
- A setting in the embedded widget is off but should be on.
- The widget expects a signal from the app for resize.

**Comment by teusbenschop** [comment]
![temp qrniubzh 1](https://cloud.githubusercontent.com/assets/1310167/20062612/a80f98be-a504-11e6-9943-3428334262dd.png)

![temp fajdeqxs 1](https://cloud.githubusercontent.com/assets/1310167/20062638/b956250c-a504-11e6-8af5-eb738a8dd97f.png)

These two screenshots are the ones Apple refers to.

It looks like there is repainting of both screenshots, but not in a correct fashion.

Both screenshots do not refer to kind of standard pages, but both refers to the more difficult type of pages:
- The splash screen.
- The Workspace.

**Comment by teusbenschop** [comment]
A solution to the problem is here in the Playground: https://github.com/bibledit/playground/commit/3a0ee8d195e928e39808efb8c33c9570729e9de3
