### ISSUE TITLE
Paragraph capital check needs more context sensitivity

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#393]
The check for capitals at the start of paragraphs is quite useful, but it is throwing a ton of false positives for us because we are not capitalizing the first character in lines of poetry that are continuations of previews sentences. Each sentence gets a capital, but not each line of poetry. I think there could be a user configurable toggle for whether or not `\q1` and `\q2` tags count as "starting a paragraph" for the purposes of this check.

**Comment by teusbenschop** [comment]
Sounds good. It could be a toggle, or it could be an entry where to enter tags that don't start a paragraph, separated by a space.

**Comment by teusbenschop** [comment]
This is done now, I intend to make the output clearer, e.g. showing the whole paragraph, rather than just the one offending character.
