### ISSUE TITLE
Use different paragraph end punctuation check for poetry

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#394]
The check that returns "Paragraph does not end with an end marker", (`Checks_Sentences::paragraphs()`) is a bit too aggressive. It works great when it is actually the end of a paragraph, but it mistakes lines of poetry for the end of a paragraph and complains when they don't have sentence-terminating punctuation.

In most cases (at least for the language I'm working with) adding the punctuation marks allowed inside a sentence to the list should make it work. Checking for end of sentence punctuation only needs to happen before `\b` or `\p` tags, not  before `\q1`, `\q2`, etc.

**Comment by teusbenschop** [comment]
This issue got fixed when issue #393 got fixed.
