### ISSUE TITLE
Clicking in poetry at times goes to verse 0

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#398]
Phil: In the Linux Client and the Android Client, when I tap/click somewhere in a line of poetry, instead of the focus shifting to that verse, it goes to verse 0. This may not be all the time, but happens quite frequently.
In a normal paragraph, it seems not to do that so much anymore.
I just tried clicking on a poetry line in the Cloud, and it did not go to verse 0, but to the verse I clicked.

**Comment by alerque** [comment]
I've seen something very like this but wasn't able to put my finger on what the conditions were.

**Comment by teusbenschop** [comment]
I also have seen something like this, but it was rare. But I do rarely click in any poetry, and use the keyboard nearly all of the time. That may explain it :)

**Comment by teusbenschop** [comment]
More information needed: Which one of the four different editors is it that causes this?

**Comment by alerque** [comment]
This would have been the visual-chapter editor for me. We had to use the visual-verse editor for chapters had poetry. That being said our team hasn't worked since your overhaul with Quill so this might be irrelevant now.

**Comment by teusbenschop** [comment]
Okay thank you for the information. Yes I will test it out with the Quill based editor.

**Comment by teusbenschop** [comment]
More information: https://groups.google.com/forum/#!topic/bibledit-general/rHs6RQttxiU
