### ISSUE TITLE
Internal site's URL to honour https

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#414]
When the site's URL is at http://website.org:8080, then the internal site's URL also points to that. But when the site is enforcing secure http, the URL changes to https://website.org:8081. The internal site's URL still points to the original one. Rather it should point to the secure one.

**Comment by alerque** [comment]
Internal links could use the protocol independent `://` URL scheme to make the browser fill in whatever it is connecting through. Note this should not be used for external things such as links sent out in emails or other sites linking to a BE instance, but for self referential things it could work.

That being said, why are there ever fully qualified protocol and domain links inside BE at all? Wouldn't using relative links starting from `/` do the job for all internal references?

**Comment by teusbenschop** [comment]
The word "internal" in the original comment I made was confusing. It should have been "external", that is the URL that is sent out in emails and in the RSS feed.

**Comment by alerque** [comment]
Okay that makes a lot more sense. Yes those need to reflect whatever the canonical URL is which should be in `config/userfacingurl.conf` right?

**Comment by teusbenschop** [comment]
Yes, that's right.

**Comment by teusbenschop** [comment]
But, uuhm, (scratching my head), I now think that the URL is correct already. I tested it on our own secure site, and it behaves correctly. Not sure which assumption made me to open this issue, haha.
