### ISSUE TITLE
Support for USFM 3.0 ?

### ISSUE THREAD

**Issue by DavidHaslam** [bibledit/bibledit#431]
[USFM 3.0](https://ubsicap.github.io/usfm/about/releasenotes.html) is on its way.

Bibledit developers should plan to support the new markers, revised markers, and the features and syntax improvements.

The new version is currently **3.0rc1** prerelease stage.
I expect it will be released at the same time as **ParaTExt 8.0** during 2017.

**Comment by teusbenschop** [comment]
It's good there's still some time before USFM 3.0 becomes the new standard. Thanks for drawing attention to this!

**Comment by teusbenschop** [comment]
Basically support is there now. New issues were opened for bits still to be done.
