### ISSUE TITLE
Planning year roll-over failure

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#432]
In December 2016 the Planning displayed December 2016. On 2 January 2017 the Planner suddenly displayed January 2016. It was supposed to display 2017 instead of 2016.

**Comment by alerque** [comment]
You know there was a leap second added at the end of last year right? Hopefully you're using a date library so you don't have to actually account for things like that, but hey it took CloudFlare DNS offline for 90 minutes so who knows where bugs might be lurking.

**Comment by teusbenschop** [comment]
Haha, indeed, perhaps that single second blew it up! :) I't using the C++ `<chrono>` functions. :)
