### ISSUE TITLE
Click settings - accounts: Blank screen

### ISSUE THREAD

**Issue by teusbenschop** [bibledit/bibledit#554]
On the Android app it was observed that clicking menu Settings - Accounts results in a blank screen.

* Fix that.
* Check other ports also.

**Comment by LAfricain** [comment]
I have the same problem.

**Comment by teusbenschop** [comment]
It's going to be fixed: There no 'Account" settings at all on a client, so the menu item should not have appeared. It appears now, but does nothing (except giving us a blank mind :)
