### ISSUE TITLE
Export all the books to one odt file

### ISSUE THREAD

**Issue by LAfricain** [bibledit/bibledit#560]
It would be very nice to export the project in one odt file, ready to convert it to pdf and to send it to printer...
Or it can be usable with the option master document in Libreoffice?

**Comment by teusbenschop** [comment]
When using a master document, I can't figure out how to transfer the headers from the inserted document to the master document. Right now it's taking empty headers, when starting from a new empty master document.

**Comment by postiffm** [comment]
We have a part of this capability in bibledit-desktop...where we export
usfm of multiple books into one large usfm file. Actually we import that
into some templates we use in InDesign. But I suppose we could do it
also for opendocument export. Haven't tried it.

**Comment by LAfricain** [comment]
Le 15/05/2017 à 20:27, Matt Postiff a écrit :
> We have a part of this capability in bibledit-desktop...where we export
> usfm of multiple books into one large usfm file. Actually we import that
> into some templates we use in InDesign. But I suppose we could do it
> also for opendocument export. Haven't tried it.

Yes but till today for me export with BB-desktop doesn't runs well...

**Comment by postiffm** [comment]
Am I correct: that is because of the 12,0 problem?
    
    On 5/16/2017 5:04 AM, LAfricain wrote:
    
    
      
      Le 15/05/2017 à 20:27, Matt Postiff a écrit :
      > We have a part of this capability in bibledit-desktop...where
      we export
      > usfm of multiple books into one large usfm file. Actually we
      import that
      > into some templates we use in InDesign. But I suppose we
      could do it
      > also for opendocument export. Haven't tried it.
      
      Yes but till today for me export with BB-desktop doesn't runs
      well...
      >
      >
      >
      > —
      > You are receiving this because you authored the thread.
      > Reply to this email directly, view it on GitHub 
      >
<https://github.com/bibledit/bibledit/issues/560#issuecomment-301578349>,

**Comment by LAfricain** [comment]
Le 16/05/2017 à 11:54, Matt Postiff a écrit :
>
>
>
>
>
> Am I correct: that is because of the 12,0 problem?

Yes, and now I don't know why I have a empty odt file... I post about 
it, on the old issue. And It's true that the layout with BB is really 
beautifull compare with BB-desktop. For instance the number of the 
chapter is include in the text as a big Number (lettrine in French).

**Comment by teusbenschop** [comment]
If Bibledit-Desktop would have the option to send and receive to/from Bibledit Cloud, the whole export issue would be solved for Bibledit-Desktop. It could then sync its USFM to the Cloud, and the Cloud could be set up to export every night, so there would be one single OpenDocument file for the entire Bible.

**Comment by teusbenschop** [comment]
Another advantage would be that a mixed setup would be possible: Some people translate through Bibledit-Desktop, other people would proofread that text on their mobile phones.

**Comment by LAfricain** [comment]
Le 16/05/2017 à 17:46, Teus Benschop a écrit :
>
> If Bibledit-Desktop would have the option to send and receive to/from 
> Bibledit Cloud, the whole export issue would be solved for 
> Bibledit-Desktop. It could then sync its USFM to the Cloud, and the 
> Cloud could be set up to export every night, so there would be one 
> single OpenDocument file for the entire Bible.
>

Yes it would be wonderful... Would it be possible too with BB-cloud in 
local network?
Can you help the dev of BB-desktop to perfom the export process?

**Comment by teusbenschop** [comment]
1. Yes, it would also be possible when the Cloud runs on the local network.

2. I am too busy on Bibledit (plain) to be able to help with Bibledit-Desktop.

3. Another way that is possible, right now, is to connect Bibledit-Desktop to a git repository (if that option is still there), then to connect Bibledit-Cloud to that same git repository, and sync the data this way.

**Comment by LAfricain** [comment]
Le 16/05/2017 à 19:50, Teus Benschop a écrit :
>
> 1.
>
>     Yes, it would also be possible when the Cloud runs on the local
>     network.
>
Ok
>
> 1.
>
>
> 2.
>
>     I am too busy on Bibledit (plain) to be able to help with
>     Bibledit-Desktop.
>
Pity :'(
>
> 1.
>
>
> 2.
>
>     Another way that is possible, right now, is to connect
>     Bibledit-Desktop to a git repository (if that option is still
>     there), then to connect Bibledit-Cloud to that same git
>     repository, and sync the data this way.
>
Yes the it is, can give some explanation how to do? Maybe to do a test 
with your Bible in ndembele?

**Comment by teusbenschop** [comment]
In our team we're using this system, but instead of Bibledit-Desktop, we use the last available version of Bibledit-Gtk. (Yes, we should update to Bibledit-Desktop, I know, because of its improved functions - but our translation project is nearing completion, so I won't bother to upgrade...) So with Bibledit-Gtk it's possible, for sure. When Bibledit-Desktop still has the option to connect to a git repository, it should be possible.

Info for Bibledit-Desktop, I don't have.
Info about Bibledit and a git respository is here: https://bibledit.org:8081/collaboration/index - that is menu Settings / Repository. Plus here: https://github.com/bibledit/cloud/blob/master/config/config.txt.

**Comment by postiffm** [comment]
Hi guys--Bibledit-desktop still has all the functionality that Bibledit-gtk had before, so it should be able to connect with a git repository. We have not changed any of that code (at least consciously!). 

Bigger picture, it seems to me that importing the new-and-improved opendocument export code from Bibledit cloud into Bibledit-desktop would be the best way to accomplish what you want to accomplish. I have not looked into that possibility yet, but I hope to do so. 

LAfricain, could you could send me an email with a sample of the output of both bb-desktop and bb-cloud. so I can see the difference you are talking about? I have never used bb-cloud (which I guess is also called bibledit-plain?), and I don't know the first thing about setting it up to work properly.

**Comment by LAfricain** [comment]
Ok I tried but it failed.
I begun to create a new folder in my github repository and I entered the 
url in BB-cloud :
https://github.com/LAfricain/lafricain.en.vrac/NYM
Result:
remote: Not Found fatal: repository 
'https://github.com/LAfricain/lafricain.en.vrac/NYM/' not found failed 
because of read access.

I need more information.

**Comment by teusbenschop** [comment]
It won't work with a new folder in an existing github repository. It needs a new and clean repository. In your case, for example, it would be to create LAfricain/NYM repository, and then connect to it like:

https://username:password@github.com/LAfricain/NYM.git

It uses your personal credentials to access. Without those, it cannot write to that repository.

**Comment by LAfricain** [comment]
Ok I progress... But I can't see the books on github, I have still this 
error:
Les modifications ont été poussées vers le dépôt avec succès.
Stocker les données bibliques locales dans la zone d'attente.
Les données bibliques locales ont été ajoutées avec succès.

Erreur: Repo could not be reach
Validation failed....

Échec de la validation des données bibliques locales. Sur la branche 
master Votre branche est à jour avec 'origin/master'. rien à valider, la 
copie de travail est propre

**Comment by LAfricain** [comment]
I did it again it's ok!

**Comment by LAfricain** [comment]
No I spoke quickly... I have no error on BB-cloud but I can't see the 
books on Github.
I tested now with BB-desktop it seem to runs well...

**Comment by LAfricain** [comment]
Sorry!!!!!!!!!!!!!!!!
It's ok ! It's ok. I needed to wait a little bit. Waouh this is nice !

**Comment by LAfricain** [comment]
Ok now I know how to do, but if I want to give access to an another 
person, without giving my login and password how to do?

**Comment by teusbenschop** [comment]
I guess that with a personal repository on github, it is required to pass your username and password to others. There's no other way with a personal repository.

The way forward looks to be to create a "team" on github, then assign the individual members to that team.

Or else to create a different personal repository, not owned by you, but just a general username, so the username and password can be freely shared among the translation team members.

**Comment by LAfricain** [comment]
Le 17/05/2017 à 10:30, Teus Benschop a écrit :
>
> I guess that with a personal repository on github, it is required to 
> pass your username and password to others. There's no other way with a 
> personal repository.
>
> The way forward looks to be to create a "team" on github, then assign 
> the individual members to that team.
>
Ok
>
> Or else to create a different personal repository, not owned by you, 
> but just a general username, so the username and password can be 
> freely shared among the translation team members.
>

This seems to be a good idea.

**Comment by LAfricain** [comment]
Le 17/05/2017 à 10:30, Teus Benschop a écrit :
>
> I guess that with a personal repository on github, it is required to 
> pass your username and password to others. There's no other way with a 
> personal repository.
>

Maybe this way : 
https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/ 
?

**Comment by teusbenschop** [comment]
Looks good, that link to the article.

**Comment by postiffm** [comment]
I don't know if this is helpful, but bibledit-desktop has a newer feature where you can export the whole Bible into one large USFM file. Go to File | Export, choose Bible, tell it which Bible, then choose USFM, then everything, then check the option "For USFM, combine files into one. This will produce one huge USFM file. Can you then import that into bb-cloud and do what you want to do with it?

**Comment by LAfricain** [comment]
Yes it's a good idea. But I Think Teus already closed the bug and add 
the option in Bibledit. For information you have, Bibledit and 
Bibledit-cloud. BB is like Bibledit-desktop, you can work on your 
computer. BB-cloud give you the opportunity to combine and centralise 
all the jobs. But with BB as with BB-D, you can  connect to git.

**Comment by LAfricain** [comment]
A question.
For me it's ok, I undestand the way to use git with BB-cloud. My 
question is is it possible to use git directly with BB? Or it's 
necessary to install BB-cloud? I tested with an other computer, when I 
click on Send/Receive it connects to the local server. But if I want to 
connect directely to git, as with BB-desktop  is it possible?

**Comment by teusbenschop** [comment]
No, it is not possible to connect a Bibledit client directly to a git repository. It always needs to go via Bibledit Cloud.

**Comment by LAfricain** [comment]
Ok  thank you for answer!
