### ISSUE TITLE
make localized stylesheet possible

### ISSUE THREAD

**Issue by LAfricain** [bibledit/bibledit#561]
I would be very nice to have the name of the style translated in other language (for me French). Because for people who doesn't know English it can be difficult to understand what's means the name of the English style...
Than I request it to be localized.

**Comment by LAfricain** [comment]
Is it possible to translate it on launchpad?

**Comment by teusbenschop** [comment]
Yes, that is possible. Tonight the new bibledit.pot is supposed to be sent to Launchpad. Then Launchpad will import it after a while. After that, it should be translatable.
