### ISSUE TITLE
Make verification of non-break space between certain punctuation possible

### ISSUE THREAD

**Issue by LAfricain** [bibledit/bibledit#562]
In French we have non-break space between the «» ! ? : ; punctuation, but actually Bibledit doesn't propose this verification, that can be very useful in French.

**Comment by teusbenschop** [comment]
* If there's a plain space, not a non-break space, is that an error in this situation, or can it be considered okay also?

* How does the user enter the non-break space?

* What is the Unicode value for this non-break space?

**Comment by LAfricain** [comment]
Le 17/05/2017 à 14:46, Teus Benschop a écrit :
>
>  *
>
>     If there's a plain space, not a non-break space, is that an error
>     in this situation, or can it be considered okay also?
>
It's better to use the non-break-space, with libreoffice if you use the 
plain space it's considered as an error.
>
>  *
>
>     How does the user enter the non-break space?
>
On linux ALT-GR and N, but with the word processor it's automatic.
>
>  *
>
>     What is the Unicode value for this non-break space?
>
U+00A0

**Comment by teusbenschop** [comment]
Okay, thanks for the information.

How would one enter this non-break space on iOS and on Android?

**Comment by LAfricain** [comment]
Le 17/05/2017 à 16:29, Teus Benschop a écrit :
>
> Okay, thanks for the information.
>
> How would one enter this non-break space on iOS and on Android?
>
?? I think on Android it's automatic with french. I can test it.

**Comment by LAfricain** [comment]
Android add non break space automaticly if you are with the French keyboard
