### ISSUE TITLE
Conflict with the bibledit.xpm picture on Ubuntu

### ISSUE THREAD

**Issue by LAfricain** [bibledit/bibledit#568]
When installing the two apps (bibledit and Bibledit-desktop) with a deb (created with checkinstall for BB-desktop). I have a conflict with the  bibledit.xpm picture.
It needs to be renamed. 
See : https://github.com/postiffm/bibledit-desktop/issues/19

**Comment by teusbenschop** [comment]
With the fix in Bibledit-Desktop, that icon is named 'bibledit-desktop', which matches the package name. I suppose that this is enough to fix the conflict.
