### ISSUE TITLE
Input cursor jumping around

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#91]
I [reported this on the mailing list](https://groups.google.com/d/msg/bibledit-general/OZduAty8bKM/A7xm-iHFBAAJ) mostly to see if I was doing something wrong that there was a known fix for, but the more I look at it the more it seems like a serious code bug, so I'm opening an issue report to track it along with the relevant source code changes.

The input cursor (caret) is not staying put while typing in either the visual chapter editor _or_ USFM chapter editor. While typing the input focus will jump around to strange places, both forward and backward, often to other verses.

This same behavior is present on:
- Bibledit Cloud 1.0.364
  - Firefox 45 Linux
  - Chrome 49 Linux
  - Firefox 44 OS X
  - Chrome 48 OS X
  - Chrome 49 on Windows
- Bibledit Mac 1.0.361 (15) on OS X El Capitan

**Comment by alerque** [comment]
Confirmed fixed in newly released cloud version 1.0.397 (at least in USFM chapter editor  under Chrome 49/Windows).

**Comment by teusbenschop** [comment]
Great!

**Comment by alerque** [comment]
Also working from the same Cloud install to FF on Linux, so I'm going to call this fixed. Apparently this was just a matter of releases not being rolled since it was talked about and fixed weeks ago? How frequently does the Apple App Store update? Should I switch to manually updating that rather than using the App Store version?

**Comment by teusbenschop** [comment]
The Apple App Store usually approves a newly submitted Bibledit update within a week or so. I think the Apple App Store is not the problem, but the problem is just me: I should have a regular update schedule, so as to submit updated apps in time. And I was a bit slack in this. :)

**Comment by alerque** [comment]
You could just as easily say the problem is me. I'm the one working on Makefile and other mechanics that tag, build, release, distribute and install updates without so much manual intervention required at each step!

**Comment by teusbenschop** [comment]
:)
