### ISSUE TITLE
Redirects improperly adding domain/port into

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#93]
I'm trying to run Bibledit Cloud behind a proxy (so that I can secure it via SSL between the user and the server). It mostly works but there are a few rough edges. Some of the built in redirects prepend the domain and port to the URL even when they don't need to. Changing the resulting URL manually back to the right domain usually works, but the redirect shouldn't have stuffed the domain into the mix in the first place. The interface should be able to function with know knowledge of what domain the user's browser is actually hitting up.

**Comment by alerque** [comment]
This appears to be at least in part because of `get_base_url()` function on [Line 40 of  lib/filter/url.cpp](https://github.com/teusbenschop/bibledit/blob/b3f07afc2773c53b0f65637c42287f7edf99c8b0/lib/filter/url.cpp#L40). The value of `request->host`and friends are only the values Bibledit knows that it was requested from, they may or may not be the values that need to be passed back to the user. These should either be removed so that only relative redirects are passed around or a check should be made for what the proxy server is reporting as user's actually request. 

For example note the disparity between the request my browser sends trying to login to Bibledit vs. what it gets told to load as a Location in the response headers:

![selection_186](https://cloud.githubusercontent.com/assets/173595/13879818/18b7a8d6-ed22-11e5-8500-882cc22411a9.png)

**Comment by alerque** [comment]
This problem can be partially mitigated with advanced options of some proxy servers to munge the headers as they pass through each way. For example Apache's `ProxyPassReverse` directive can manually catch location headers that need to be re-written. Confusingly since Bibledit is guessing the domain itself (from browser based info it shouldn't be touching) rather than using the incoming request headers that the proxy server passes, this has to be filled out with a mismatch from the other proxy settings in order to work. If anybody else hits this problem I might be able to help them configure their proxy to work, but really this should be fixed in Bibledit at some point. Also (see next issue) it's only a partial band-aid.

**Comment by teusbenschop** [comment]
It is a new thing for Bibledit to run behind a proxy. It has never been tested. Glad you found some of the rough edges that may then be fixed. I agree that fixing it is the best one can do, rather than to have an difficult proxy configuration.

**Comment by teusbenschop** [comment]
The easier solution would be to redirect to a relative URL.
But a location header needs to contain an absolute url, like http://localhost/some.
See 14.30 in the specification https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html.
That means that this solution would not be possible in this case.

**Comment by alerque** [comment]
I think this is why a lot of apps have a configuration value for what their official user facing domain is—because the domain the app sees itself on may or may not be the one the user is seeing it on. It might not be possible to detect this, but having an option to _set_ the value instead of assuming the detection is working would resolve this issue. I think.

**Comment by teusbenschop** [comment]
After looking through some documentation on what a proxy server does to the HTTP headers, it looks like the suggestion to make a configuration value for the user-facing domain is the most fool-proof solution. Even if it were possible to detect the correct domain and port from one proxy server, it might not be possible to extract that information from another type of proxy server.
So I'll start on adding this setting to the interface of Bibledit.
Of course, the best thing would be that Bibledit would support secure HTTP. Then there would not be a need for the proxy that secures the traffic. 
But even then, a user may find a proxy between the browser and the server, and that proxy might be out of the control of the user.
So taking all bits in account, just making that setting would resolve the situation in all cases.

**Comment by alerque** [comment]
Yes, Bibledit should support HTTPS internally for other reasons, but it should also deal with being proxed by something external. Other use cases might be to load balance servers or toggle between installations for maintenance. Basically anything that has it's own built in HTTP server and daemon process adds a level of complexity to sysadmin routines and sticking them behind proxies is a common way to avoid downtime, provide secure services that integrate with other services on a domain, etc.

**Comment by alerque** [comment]
Case in point, I have one URL for out team and they have it bookmarked and always work as usual. This is an HTTPS domain they can reach from anywhere and normally it's proxied to the release version of BIbledit, but I can also role individual users / ips / vpn groups over so that their proxy requests hit a devel server running my own git version.

**Comment by teusbenschop** [comment]
That means that the use cases would be many, and Bibledit should be able to deal with all of them. Enough reasons to get that setting in :)
