### ISSUE TITLE
Data files need trailing EOL

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#96]
The `Ref/x/data` files stored it git by Bibledit don't have ending newlines on them. This isn't technically invalid, but it makes it a royal pain to work with them across other editors as most software defaults to adding trailing newlines. Defaulting to having the trailing newlines would make the workflow interaction with external edits much smoother.

**Comment by teusbenschop** [comment]
It would be good to follow the practise used by other USFM editing software, the main one of which is Paratext. I haven't checked what that software does, whether it adds a new line to the last line, or whether it omits it.

**Comment by alerque** [comment]
Speaking of that, is there some reason the data file layout isn't just following the USFM convention? I'm use the raw git repo to run other  tools on but have to morph the file layout to get a standard USFM layout. What's the rational behind having USFM format data files but not keeping them in a standard layout?

**Comment by teusbenschop** [comment]
I agree that following the USFM standard is best.

I did a quick check on http://paratext.org/about/usfm to find whether it mentions the EOL to the last line, but could not find it. It could be there, but I just could not find it on a quick check.

What changes do you have to make to the current layout to get to a standard USFM layout?

**Comment by alerque** [comment]
Having `.usfm` file name extensions would help.

Do you have a working copy of Paratext to compare how it saves USFM files? The "export USFM" feature of Bibledit already includes trailing newline at EOF, it's just inconsistent in its internal storage.

**Comment by teusbenschop** [comment]
Yes, I have a woking copy of the Paratext 7. I opened a book, made changes to it, and saved it. Opening it in TextEdit showed that it did not have the trailing EOL. The caret of TextEdit could not move to a new line, but remained at the end of the last line.
The name of the file was 01GENMP1.SFM

**Comment by alerque** [comment]
Pardon my not trusting TextEdit, but better text editors than that sometimes fail to actually reveal how the file terminates in the name of smoothing things over for end users. Try this trick from a terminal to see if (a newly generated file clean out of Paratext and not edited elsewhere) has a newline at the eof:

```
tail -n1 01GENMP1.SFM | tr '\n' ¶
```

That should show you the last line of the file with the newline (if present) replaced with a pilcrow so you can _see_ whether it's there or not.

I found some other `.SFM` files around on the web, but `.usfm` seems to be more standard these days and (as in BE's current export function) works fine in the other apps that expect it. I'm  wondering if that naming scheme isn't a hold over from the days when 8+3 was the max filename most systems could cope with. Does Paratext's import have any issues with files named `<filename>.usfm`?

**Comment by teusbenschop** [comment]
Yea, editors are not always that straight, but at times may try to smooth out things for the users.
Just to be sure, I have attached a zip file with two files:
The _MP1_ one was an existing file in Paratext, not sure where it came from.
The _EOL_ one comes from a newly created project in Paratext, and I've added text to Matthew 1:1, then saved it.
I tried importing a file with the .usfm extension to Paratext, and it works without issues.

[usfm.zip](https://github.com/teusbenschop/bibledit/files/187857/usfm.zip)

**Comment by alerque** [comment]
So from that zip 01GENMP1.SFM does not have a trailing line break but 41MATEOL.SFM **does**. It actually has Windows CRLF breaks (carriage return + line feed) throughout including before the EOF so that's another whole kettle of fish, but that  problem is much more easily solved because `git` and friends have built in tools for [transmogrifing](http://calvinandhobbes.wikia.com/wiki/Transmogrifier) so that collaborators can work with their native formats without worrying about what other editors do. In any event it includes a trailing line break @ EOF.

Given that you don't know where the Gen file came from and, at least in the last few years, most text editors have been standardizing on including the newline as in your current sample from Paratext I think it makes sense to standardize on that as well. Besides making it easier on external editors not to include bogus stuff in git commits, this also makes compiling a roll-up of a book from all the chapter data files as easy as concatenating them together. Currently  it requires an extra step of echoing a line in between each file.

**Comment by teusbenschop** [comment]
The reasons given definitely convince me that adding trailing new line ("\n") characters is the right thing to do for the internal representation of the USFM.

**Comment by teusbenschop** [comment]
It new has a trailing new line in the internal USFM storage for any Bible chapters saved from now on. Existing Bible chapters are left as they are.
