### ISSUE TITLE
Replace visual editor with ProseMirror

### ISSUE THREAD

**Issue by alerque** [bibledit/bibledit#97]
Preface: _This isn't something that one commit over the weekend is going to fix, but I'm opening this issue report to suggest a long term enhancement trajectory._

The current visual chapter & verse editor interface sucks —I'm sorry there isn't a nicer way to put this— and it needs to be completely overhauled. However the issues with it are not entirely the fault of the current implementation, a lot of the chaos is caused by browsers and their assorted foibles with content-editable areas. As far as I can tell no amount of patching on top of content-editable is going to do more than putting band-aids on dry bones.

I propose completely gutting it and replacing it with [Prose Mirror](http://prosemirror.net/) with a custom content schema that maps to USFM. The USFM editor could also be replaced with [Code Mirror](http://codemirror.com/) to round out the effect and bring sanity  to the whole team.

**Comment by teusbenschop** [comment]
Yes, the visual editors may suck, but they have sucked more in the past, and are getting better bit by bit. However I've very often thrown up my hands in despair about issues, how to fix them, and often prayed about it, put down the tools, start on another project, come back to the editors, and so on.

If you think that Prose Mirror and Code Mirror will assist, that would be great.
I propose that then a new editor, based on prose mirror, is added to the current four editors, so that there's going to be five Bible text editors, till such time that the new editor based on prose mirror completely replaces the current visual editors. The new editor could be labelled 'experimental', and anyone could try it out and give feedback.

It would be great to have a good editor that does not suck! :)

**Comment by alerque** [comment]
That sounds like a reasonable migration plan. From a code refactoring standpoint it would be better to put it in a feature branch, but getting feedback and testing is going to be hard if it isn't released in a way that people can play with it in production without screwing up their workflows before its good and ready to be the only editor(s).

It's going to be a little bit tricky because the way I would approach it would require a little bit different interface with BE than currently exists, but maybe it can be shimmed or done in stages to those refactors don't end up being disruptive.

**Comment by teusbenschop** [comment]
It is also possible to make a setting in the interface whether to enable the experimental features. That setting would be off normally, so by default no one would see it, and cannot screw up their Bibles. When enabled, the experimental editor would appear in the menu.

A new interface requires new videos also to be uploaded to YouTube and Vimeo, but in any case, when the new interface makes things more intuitive for the average users, then that's worth it.

Good luck, brother, in Jesus' Name!

**Comment by alerque** [comment]
Thanks, I have a feeling I'll need it whenever I get time to give it a shot. In the mean time I'm content with my one [evil genius contribution](https://github.com/alerque/bibledit/commit/1f363a5f44b8352974e42b215cc61586e993a472) for today.

**Comment by alerque** [comment]
ProseMirror recently got a complete refactoring using a much more modular architecture that will make this a lot easier to implement!

**Comment by teusbenschop** [comment]
Would you like me to create a page in Bibledit with a basic demo of ProseMirror?

**Comment by teusbenschop** [comment]
The ProseMirror editor at http://localhost:8080/editpm/index doesn't work at all yet, but my time was up, so I just committed what was there.... to be continued...

Observations so far:

The page is an orphan: It cannot be reached from anywhere within Bibledit.

It causes the CPU to run at a relatively high percentage while editing (measured without CSS yet).

The backspace and similar do not work in the demo.

**Comment by teusbenschop** [comment]
Including the prosemirror.css stylesheet according to https://prosemirror.net/guide/basics.html fixed the problem of high CPU usage.
`<link rel="stylesheet" type="text/css" href="prosemirror.css">`
Reading the documentation is always good, of course, but who can ever imagine that including a simple .CSS reduces CPU usage.

**Comment by teusbenschop** [comment]
The current demo at http://localhost:8080/editpm/index is based on the online basic ProseMirror demo https://prosemirror.net/demo/basic.html, and does more or less them same.

**Comment by teusbenschop** [comment]
I've been doing playing with ProseMirror but find it hard to grasp and work with, and therefore I think I'll also look into Quill (https://quilljs.com/) as it's similar to ProseMirror.

**Comment by teusbenschop** [comment]
There is also Trix (https://trix-editor.org/), which also side-steps the limitations of contenteditable, just like ProseMirror and Quill do.

**Comment by teusbenschop** [comment]
It looks there's native class editing capabilities (a feature Bibledit relies on) in Quill, see the demo at the playground at http://quilljs.com/playground/#class-vs-inline-style. I have not yet found that capability, natively, in ProseMirror. It may be there, but I just have not yet found it.

**Comment by teusbenschop** [comment]
I am kind of failing to wrap my head around the inner workings of ProseMirror and so fail to properly implement it. Code for a very basic page is in the library in /editpm/\* . It can be used as a starting point for further development.

**Comment by teusbenschop** [comment]
A new visual chapter editor has now been implemented. See https://github.com/bibledit/bibledit/issues/388. 

It is based on Quill. 

Quill is similar to ProseMirror in that it does not use contenteditable in the DOM to store the editor. Rather the editor is stored in memory, and the contenteditable is only used as a user input device.
